### ISSUE TITLE
Android  发送HEIC格式得消息 异常 

### ISSUE THREAD

**Issue by wukuiqing49** [tencentyun/qcloud-documents#10160]
errCode:8004
errMsg:File upload cos success but ci transfer error:Invalid image code:-2 X-ReqId: X-ErrNo:-443

imSdk版本:5.1.56

**Comment by v-guanhuang** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您的问题我们已经收到，并已提交给相应团队进行评估，我们会尽快完成评估，非常感谢您！
若使用中还存在其它问题，您可通过 IM 技术交流 [联系我们](https://cloud.tencent.com/document/product/269/59590) 或 [腾讯云专栏](https://cloud.tencent.com/developer/user/5022866)，我们收到后会尽快处理。
感谢您的支持，祝您工作顺利！
