### ISSUE TITLE
群成员数量不准问题

### ISSUE THREAD

**Issue by andzou** [tencentyun/qcloud-documents#10182]
拉了新的群成员入群，getGroupsInfo拿到的getMemberCount还是旧的数量，杀死进程重新打开app拿到的getMemberCount才是正确的

**Comment by chengqw** [comment]
麻烦问下群类型是什么？

直播群请使用接口：
 /**
     * 2.8 获取指定群在线人数
     *
     * @note 请注意：
     *   - 目前只支持：直播群（AVChatRoom）。
     *   - 该接口有频限检测，SDK 限制调用频率为60秒1次。
     */
    public abstract void getGroupOnlineMemberCount(String groupID, V2TIMValueCallback<Integer> callback);


其他群使用getGroupsInfo可获取人数。


如果有问题，麻烦同步详细场景和log看下哈
