### ISSUE TITLE
关于V2版本与V1版本的SDKAPI问题

### ISSUE THREAD

**Issue by WS-Vincent** [tencentyun/qcloud-documents#10250]
我们项目里面用到即时通讯的SDK与外部第三方是共用的。
由于诸多历史原因，SDK 目前用低版本 5.1.6.2。
SDK的初始化及登录是外部SDK封装了，用的是V1版本，我目前用的是V2版本SDK，由于覆盖业务太多，目前已经无法拆了。
想咨询一下 V2版本的SDK的初始化 与V1版本的SDK初始都调用了的情况下 是否会对两遍的SDK的通信有影响。
我目前遇到的问题是没有调用initSDK这个API，导致无法建立正常的消息收发链路。还望可以回复一下。

**Comment by Junkmer** [comment]
首先先说一点
1. 一个应用程序同时引入IM SDK 基础版（V1）、增强版（V2）是会出现库冲突的，也就是编译器就会报错。
2. 对于IM SDK，V1、V2 api是不能混用的，混用会出现无法预知的问题，这个是无法修复的

综上所述：

V2版本的SDK的初始化 与V1版本的SDK初始都调用了的情况下 是否会对两遍的SDK的通信有影响
-----------------
有影响

没有调用initSDK这个API，导致无法建立正常的消息收发链路
-----------------
使用不当会出现此问题

方案建议：
对于之前业务集成的IM SDK基础版，强烈建议升级。辛苦一时，幸福一世。

加油开发者，你可以的

**Comment by WS-Vincent** [comment]
首先能明确的是，IMSDK是无法升级，也就是用最新版本。。。因为里面牵扯到的业务太大了，已经好几年了，还涉及到外部SDK公用。
我一开始以为API的 V2TIMManager 是兼容 TIMManager的 ，导致我组件开发完，测试OK之后放到主工程无法建立通信了，心态有点蹦(开发了2个月)
这几天也是一直在测试 是否 在V2初始化之后 然后继续初始化V1 。能保证双方的数据链路都OK 互不干扰。

最差的情况是我将现在V2全部推翻，然后继续换成V1,感觉也是一份不小的工作量，只是之前跟领导说已经开发完，这个月可以测试上线(目前看来够呛,已经预感到疯狂加班了)

最后还有一个问题，V1版本的SDK的相关消息部分代理监听，我看是不支持多代理转发的，是否是说A和B需要再自己的业务里面不断的来回设置。例如 TIMUserConfig的 refreshListenter。（一开始就是考虑到V1的API设计部分局限性所以用的V2）

最后 感谢回复
