### ISSUE TITLE
Command Run Fail in Windows10

### ISSUE THREAD

**Issue by qiuxin** [tencentyun/qcloud-documents#10338]
C:\Users\Administrator>tccli cvm DescribeRegions --output table
usage: tccli [options] <command> <subcommand> [<subcommand> ...] [parameters]
To tccli help text, you can run:

  tccli help
  tccli configure help
  tccli service[cvm] help
  tccli service[cvm] action[RunInstances] help

'gbk' codec can't decode byte 0x80 in position 93: illegal multibyte sequence

C:\Users\Administrator>

**Comment by HS-Gray** [comment]
我们这边并没有出现这个问题，如果你用的是3.0.557.1以及之后的版本，可以在～/.tccli/log的路径下看到日志，里面有堆栈信息，可以帮助排查问题，如果还有其他问题，欢迎来讨论

**Comment by vyixzheng** [comment]
尊敬的腾讯云用户，您好！
由于您长时间未回应，我们对反馈单进行关闭处理。
若使用中还存在其它问题，欢迎继续在官网反馈，我们收到后会尽快处理。
