### ISSUE TITLE
防止录屏继承哪个activity

### ISSUE THREAD

**Issue by Haibeike01** [tencentyun/qcloud-documents#10369]
里面提到的防止录屏有一套sd，继承里面安全的activity即可，麻烦是哪个activity

**Comment by xlwxie** [comment]
您好，具体的activity是“antiJackActivity”。

**Comment by Haibeike01** [comment]
OK，谢谢你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月11日(星期五) 下午4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tencentyun/qcloud-documents] 防止录屏继承哪个activity (Issue #10369)





 
您好，具体的activity是“antiJackActivity”。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
