### ISSUE TITLE
内容安全定价门槛问题

### ISSUE THREAD

**Issue by modstart** [tencentyun/qcloud-documents#10408]
我们拥有大量的中小企业客户，内容安全的定价门槛（4000起180万条）有点高，大部分安全运营1年也用不了那么多，可否有适合中小企业的定价策略

**Comment by vsmxshen** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，目前内容安全暂时没有调整价格的计划。
感谢您的支持，祝您工作顺利！
