### ISSUE TITLE
关于oppo手机离线推送调试不同的问题

### ISSUE THREAD

**Issue by jipengzheng** [tencentyun/qcloud-documents#10414]
目前小米和vivo都能正常通过离线推送，但是oppo手机离线推送无论怎么样都不能通，可以确定的是已经正常拿到了oppo的regid并绑定，确认创建了通知的channelId，使用的oppo的sdk跟个推是一个，但是个推的离线推送可以走通，从日志上看不出任何端倪，希望可以给予一些可能出现问题的提示。

**Comment by v-guanhuang** [comment]
请问可以提供更多信息吗？ 比如：机型， 系统版本，操作路径， 完整的log
