### ISSUE TITLE
未成年人为什么不能在腾讯云实名认证

### ISSUE THREAD

**Issue by qitayun** [tencentyun/qcloud-documents#10753]
未成年人为什么不能在腾讯云实名认证

**Comment by vrongchao** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，基于个人信息保护要求，及未成年人在实践中存在较高法律风险，存在被不法利用的可能性较高，实名认证需要满18岁。
如果遇到文档使用相关问题，欢迎通过官网反馈，我们收到后会尽快处理。
如果遇到产品使用相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
感谢您的支持，祝您工作顺利！
