### ISSUE TITLE
bug: 搜索出很多无效结果

### ISSUE THREAD

**Issue by chen56** [tencentyun/qcloud-documents#11421]
![image](https://user-images.githubusercontent.com/2039742/161261464-13d9e4ae-0456-4a26-8bc3-6b0a88c2df32.png)
进入页面后发现，并不存在搜索的关键字

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您的意见我们已经收到。
经检查，确认存在不足，我们尽快优化，给您带来不便，非常抱歉。
若使用中还存在其它问题，欢迎到官网反馈，我们收到后会尽快处理。
