### ISSUE TITLE
人脸核身什么时候上线flutter版本

### ISSUE THREAD

**Issue by lan2000** [tencentyun/qcloud-documents#11432]
如题

**Comment by vhyyhhu** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service)  或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
再次感谢您的支持与关注，期待提出更多建议！
