### ISSUE TITLE
qcloud-documents/product/安全服务/云防火墙/购买指南.md 缺少vpc防火墙价格

### ISSUE THREAD

**Issue by chen56** [tencentyun/qcloud-documents#11523]
qcloud-documents/product/安全服务/云防火墙/购买指南.md 缺少vpc防火墙价格

**Comment by vsmxshen** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，开通 VPC 间防火墙的费用目前暂时不对外公布。        
如果您需要使用 VPC 间防火墙请 [联系我们](https://cloud.tencent.com/online-service) 进行购买开通。
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/online-service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
