### ISSUE TITLE
服务端签名上传问题

### ISSUE THREAD

**Issue by Tangerg** [tencentyun/qcloud-documents#11563]
![image](https://user-images.githubusercontent.com/37281233/162926164-2fe4b700-c7d6-487c-b983-5c2a47a7ae78.png)

不是说与aws兼容吗，为什么我用aws的服务端签名，前端上传会失败
![image](https://user-images.githubusercontent.com/37281233/162926544-8660bc1d-8106-4691-981b-00863430692e.png)
![image](https://user-images.githubusercontent.com/37281233/162926602-79ab5e8f-422e-4068-8190-7d8380275ea9.png)

**Comment by Tangerg** [comment]
还是说我理解有误，aws签名只是他们提供的一个算法得自己实现一下，并没有集成到SDK里面，所以不兼容

**Comment by vwruwang** [comment]
非常感谢您的反馈，根据您反馈信息，无法确认不兼容的语言类型。建议您前往 [联系我们](https://cloud.tencent.com/document/product/436/37708) 文档 加群与该产品团队沟通。
