### ISSUE TITLE
Swift 项目中集成TUIConversation后出现问题

### ISSUE THREAD

**Issue by StephentTom** [tencentyun/qcloud-documents#11571]
#import "TUICommonModel.h" 出现爆红：
Include of non-modular header inside framework module 'TUIConversation.TUIConversationCell': xxx/Build/Products/Debug-iphoneos/TUICore/TUICore.framework/Headers/TUICommonModel.h'

**Comment by 173315179** [comment]
这个是没有找到TUICommonModel.h 文件，乔接文件里面加一下TUICommonModel.h 看看

**Comment by StephentTom** [comment]
我使用的是组件化，
![image](https://user-images.githubusercontent.com/12389738/163504642-e2db0a23-17ca-476c-9bfe-a350c56de1fd.png)
就是找不到解决的方式？？

**Comment by qiucen** [comment]
<img width="668" alt="截屏2022-04-26 上午10 28 32" src="https://user-images.githubusercontent.com/59394435/165207729-94e9c5ff-c498-452f-b8c7-31cdd9cf43be.png">
![Uploading 截屏2022-04-26 上午10.28.32.png…]()
pod集成，编译报错，TUIChat和TUIConversation都有同样问题

**Comment by 173315179** [comment]
https://www.jianshu.com/p/103c0bf7d523 参考这个
