### ISSUE TITLE
swift 项目集成obs怎么判断开始推流状态

### ISSUE THREAD

**Issue by louguoquan** [tencentyun/qcloud-documents#11676]

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
为了能更方便、准确地定位问题，需要您提供详细信息（请勿包含敏感信息），以便我们尽快核实后解决！
腾讯云文档有“文档反馈”的功能，直接在文档页面就可以反馈问题，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
如果遇到产品使用等相关问题，您也可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！

**Comment by louguoquan** [comment]
您好，邮件已经收到，我会尽快处理给您回复。谢谢！！
