### ISSUE TITLE
TDMQ-CMQ  HTTP方式队列发送、接收消息返回java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by bqingAll** [tencentyun/qcloud-documents#11816]

**Comment by v-dyjideng** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
为了能更方便、准确地定位问题，需要您补充多一点问题描述信息（请勿包含敏感信息），以便我们尽快核实后解决。
若使用中还存在其它文档相关问题，欢迎继续在官网反馈，我们收到后会尽快处理。
若使用中还存在其它产品相关问题，您可以致电 4009100100 解决，会有专人对接。
感谢您的支持，祝您工作顺利！

**Comment by v-dyjideng** [comment]
收到了哟~~辛苦啦~~~
