### ISSUE TITLE
Question: 腾讯会议 Go SDK

### ISSUE THREAD

**Issue by NICEXAI** [tencentyun/qcloud-documents#11838]
由于业务原因，需要调用腾讯会议的REST API，不过API在项目开发中可能并没有SDK那么易用，因此想问下是否考虑提供腾讯会议 Go SDK？

API文档地址：https://cloud.tencent.com/document/product/1095/42407

**Comment by v-zuofanye** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您的问题我们已经收到，并已提交给相应团队进行评估，我们会尽快完成评估，非常感谢您！
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/online-service) 或 [腾讯云社区](https://cloud.tencent.com/developer/ask) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！

**Comment by v-zuofanye** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，目前还没有这个功能，未来会上线，敬请期待！
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/online-service) 或 [腾讯云社区](https://cloud.tencent.com/developer/ask) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
