### ISSUE TITLE
COS部署静态网站的疑问

### ISSUE THREAD

**Issue by mrdear** [tencentyun/qcloud-documents#1220]
文档中开启后效果如下：
1. 访问 http://www.example.com/dir 返回 404 错误，因为根目录下没有 dir 这个文件。
2. 访问 http://www.example.com/dir/ 返回 dir/index.html 文件内容，因为 index.html 优先级比 index.htm 高。

针对1，不能提供配置吗？优先把dir当成文件处理，文件无法处理再当成目录来处理，现在使用静态博客，最后一个斜杠太容易被忽略了，然而一忽略就出现错误，很奇怪的逻辑。

**Comment by vkxianli** [comment]
可查阅https://cloud.tencent.com/document/product/436/9512
