### ISSUE TITLE
实时音视频-实时质量监控在哪里？

### ISSUE THREAD

**Issue by yxmg** [tencentyun/qcloud-documents#12359]
需要开通吗 怎么没看到入口。只看到房间通话调查

**Comment by vyunyilin** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，登录实时音视频控制台，单击 [**监控仪表盘** > **实时监控**](https://console.cloud.tencent.com/trtc/realtime-monitor)，即可进入实时监控页面。
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service)](https://cloud.tencent.com/act/event/Online_service) 或 [[提交工单](https://console.cloud.tencent.com/workorder/category)](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 **4009100100** 联系我们的客服人员，非常感谢！
