### ISSUE TITLE
【咨询】请问腾讯云文档是用什么构建的？

### ISSUE THREAD

**Issue by pxchen** [tencentyun/qcloud-documents#12500]
# 背景
最近想做个类似腾讯云帮助文档的网站，看当前开源的有mkdocs、vuepress等等，基本都是markdown转换到静态网页。

# 问题
请问是否方便告知腾讯云文档是用什么方案构建的？采用开源的还是自研的？多谢！

**Comment by wo8335224** [comment]
怎么可能开源的。内部要卷

**Comment by KyomaSan** [comment]
> # 背景
> 最近想做个类似腾讯云帮助文档的网站，看当前开源的有mkdocs、vuepress等等，基本都是markdown转换到静态网页。
> 
> # 问题
> 请问是否方便告知腾讯云文档是用什么方案构建的？采用开源的还是自研的？多谢！

朋友,你做出来了吗 我也想知道
