### ISSUE TITLE
qq分词插件既然无法识别中文和英文之外的字符，请在文档写清楚

### ISSUE THREAD

**Issue by luxurytime** [tencentyun/qcloud-documents#12562]
qq分词插件现在逻辑识别不了中文、英文以外的字符，为啥不在文档写清楚
![image](https://user-images.githubusercontent.com/12134926/177282300-a33ae597-4df3-4635-b61f-fc5927e2030f.png)

**Comment by vjunwuwu** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验， 我们深表歉意。
文档中已添加qq分词插件相应的说明。感谢您的支持与理解！

腾讯云文档有“文档反馈”的功能，直接在文档页面就可以反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
诚邀您参加：
【你找茬儿，我发奖】腾讯云产品文档“捉虫”活动
检视指定产品文档，发现和反馈有效问题，将有机会获得代金券和缤纷好礼，更多大奖等你来拿哦～
https://cloud.tencent.com/developer/article/1610407
