### ISSUE TITLE
文档缺少修改账号api

### ISSUE THREAD

**Issue by ruanjiayou** [tencentyun/qcloud-documents#12680]
控制台是可以修改账号的.api文档没写

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
腾讯云文档有“文档反馈”的功能，您可以直接在文档页面反馈问题，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
如果遇到产品使用等相关问题，您也可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
