### ISSUE TITLE
能把对应的pom依赖贴一下么

### ISSUE THREAD

**Issue by jfly0902** [tencentyun/qcloud-documents#12719]

**Comment by 97702573** [comment]
+1

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
腾讯云文档有“文档反馈”的功能，您可以直接在文档页面反馈问题，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
如果遇到产品使用等相关问题，您也可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
