### ISSUE TITLE
云点播，向观众隐瞒直播事实，会有法律效应吗

### ISSUE THREAD

**Issue by zhergd** [tencentyun/qcloud-documents#12840]
云点播，向观众隐瞒直播事实，在这基础上盈利，运营方会受到法律责任吗

**Comment by v-guanhuang** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您是否遇到云点播功能和使用上的问题，为了快速解决您的问题，您可通过 [联系云点播 ](https://cloud.tencent.com/document/product/266/19905) 或致电 4009100100 解决，会有专人对接。
若使用中还存在其它问题，欢迎继续在 [云点播官网](https://cloud.tencent.com/product/vod) 反馈，我们收到后会尽快处理。	
感谢您的支持，祝您工作顺利！
