### ISSUE TITLE
flutter文档写错了吧

### ISSUE THREAD

**Issue by yfsanfeng** [tencentyun/qcloud-documents#12963]
自实现ui集成方案/登录登出/flutter
![tencent](https://user-images.githubusercontent.com/26156700/181702175-6e6f3ef2-668d-4908-a140-1c008eb5b927.png)
登录状态对应得值是1，2，3吧
![tencent1](https://user-images.githubusercontent.com/26156700/181702381-e62bb195-a12a-436d-88cc-07d58b2c29e4.png)

**Comment by v-guanhuang** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，登录状态对应值，该文档已重新调整。
我们会不断迭代更新，并持续更新文档内容，欢迎您继续关注官网文档。
若使用中还存在其它问题，欢迎继续在官网（https://cloud.tencent.com/document/product/269/59590）反馈，我们收到后会尽快处理。
感谢您的支持，祝您工作顺利！
