### ISSUE TITLE
TCPlayer的直播回放问题

### ISSUE THREAD

**Issue by mayuxian** [tencentyun/qcloud-documents#12991]
现象：TCPlayer在自动播放模式直播回放的视频时，会触发seeked拖动结束事件，但未重新触发play事件。 
需求：因为要播放时上报观看打点，在seeked拖动结束后视频停止上报观看记录，视频重新触发play事件开始时再重新上报观看记录。
问题：因为TCPlayer在自动播放模式直播回放的视频时，触发seeked拖动上报观看记录停止，回放仍继续播放但未触发play事件所以未上报观看记录。
解决方案：
方案1.取消自动播放模式直播回放触发的seeked拖动事件
方案2.自动播放模式直播回放触发的seeked拖动事件后，再触发play事件。
麻烦把此问题转给技术或开发部门

**Comment by v-guanhuang** [comment]
尊敬的腾讯云用户，您好！
非常感谢 [mayuxian](https://github.com/mayuxian) 的反馈，产品侧不主动干预回调事件，仅转发直播回放的视频，用户在 seek 过程不需要停止上报行为。建议客户侧可以根据计算时间点，自行调整下上报逻辑。
同时，为了快速解决您的问题，您可通过 [联系云点播](https://cloud.tencent.com/product/vod) 或致电 4009100100 解决，会有专人对接。
若使用中还存在其它问题，欢迎继续在 [官网文档](https://cloud.tencent.com/document/product/266/19905) 快速反馈，我们收到后会尽快处理。	
感谢您的支持，祝您工作顺利！
