### ISSUE TITLE
cosDistCp从cos传输数据到hdfs，存在空文件时会报NPE

### ISSUE THREAD

**Issue by jianlin1993** [tencentyun/qcloud-documents#13158]
传输的文件中存在空文件时，数据传输成功，但是任务会报错
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/19817771/184308754-ad135b2e-e3f5-45cd-a89d-f1c5b91b0507.png">

**Comment by vwruwang** [comment]
此问题建议您通过提交工单来寻求帮助。
