### ISSUE TITLE
使用服务端SSE-COS 加密方式为什么上传到cos的文件访问是可以直接打开的，不应该是加密的吗

### ISSUE THREAD

**Issue by bqingAll** [tencentyun/qcloud-documents#13950]
桶SSE-COS已开启，代码跟文档里的一样

**Comment by v-guanhuang** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您是在控制台上直接访问加密的文件么？您可以在 COS 对应文档下用鼠标划词反馈问题，非常方便。
同时，为了快速解决您的问题，您可通过 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 4009100100 解决，会有专人对接。
若使用中还存在其它问题，欢迎您在官网反馈，我们收到后会尽快处理。	
感谢您的支持，祝您工作顺利！
