### ISSUE TITLE
MySQL 加密审计最佳实践 说明矛盾

### ISSUE THREAD

**Issue by LubinLew** [tencentyun/qcloud-documents#15826]
[MySQL 加密审计最佳实践](https://github.com/tencentyun/qcloud-documents/blob/master/product/%E5%AE%89%E5%85%A8%E6%9C%8D%E5%8A%A1/%E6%95%B0%E6%8D%AE%E5%AE%89%E5%85%A8%E5%AE%A1%E8%AE%A1/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/MySQL%20%E5%8A%A0%E5%AF%86%E5%AE%A1%E8%AE%A1%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md) 中说 `支持自建 MySQL、MariaDB 的 SSL 加密审计`, 但是后续设置却是关闭SSL配置, 关闭了SSL但又配置 `ssl_cipher`, 感觉前后矛盾。

**Comment by vsmxshen** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，关闭 SSL 加密、设置加密算法或在客户端连接时指定参数这三种方式，您可根据实际情况，任意选择如下一种修改方式。

**Comment by vsmxshen** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，关闭 SSL 加密、设置加密算法或在客户端连接时指定参数这三种方式，您可根据实际情况，任意选择如下一种修改方式。

**Comment by vsmxshen** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，关闭 SSL 加密、设置加密算法、在客户端连接时指定参数这三种方式，您可根据实际情况，任意选择其中一种修改方式即可。
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/online-service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
