### ISSUE TITLE
php curl查询直播码方式录制的文件列表时，curl_exec时就输出了，但是curl_exec本身返回为空

### ISSUE THREAD

**Issue by suifengtec** [tencentyun/qcloud-documents#191]
那该如何获取录制的文件列表呢？示例：

```php
//输出了文件列表
$response = curl_exec($ch);
// 但是 $response 为空。
```

**Comment by vyunyilin** [comment]
关于获取录制文件列表可通过以下方式进行，详情可参见
https://cloud.tencent.com/document/product/267/32739#.E5.BD.95.E5.88.B6.E6.96.87.E4.BB.B6.E8.8E.B7.E5.8F.96
