### ISSUE TITLE
云解析API文档有错误

### ISSUE THREAD

**Issue by fjch1997** [tencentyun/qcloud-documents#211]
https://github.com/tencentyun/qcloud-documents/blob/5f3888e35b4ecff399ce2f6fa9343887fbca37ef/api/%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1/%E5%9F%9F%E5%90%8D%E8%A7%A3%E6%9E%90/%E8%A7%A3%E6%9E%90%E8%AE%B0%E5%BD%95%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3/%E6%B7%BB%E5%8A%A0%E8%A7%A3%E6%9E%90%E8%AE%B0%E5%BD%95.md

> 其中，此接口的Action字段为DomainList。

应该是

> 其中，此接口的Action字段为RecordCreate。

同一目录下的其它文档都有同样的问题。

**Comment by vlmjlv** [comment]
已确认，文档没有问题。
