### ISSUE TITLE
Can find detail link for instance-family in DescribeInstanceTypeConfigs API page

### ISSUE THREAD

**Issue by athom** [tencentyun/qcloud-documents#215]
Can find what instance-family means in https://cloud.tencent.com/document/api/213/9391.

But I found it in the product document. 
https://cloud.tencent.com/document/product/213/2177

Maybe put the link in the api document pages?

**Comment by vwruwang** [comment]
此为旧版API，建议查阅最新API文档：https://cloud.tencent.com/document/product/213/15749
