### ISSUE TITLE
本地联调开发

### ISSUE THREAD

**Issue by CaoPengflying** [tencentyun/qcloud-documents#2156]
文档中启动本地consumer的启动参数为什么是
java ...  -jar provider-demo.jar
这不是启动provider-demo项目而不是consumer项目
按照文档所说我线上已经部署了Provider-demo项目，并且设置了provider-demo.cash文件但是启动本地的consumer报错误org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8500 [/127.0.0.1] failed: Connection refused: connect 说明他就没有去尝试连接远程服务。
我的cash文件内容为：
{
    "statusCode": 200,   # statusCode 字段必填，取值为200，表示正常状态码；请勿更改；
    "content": [{
        "service": {
            "id": "ms-gyqo83v5",   # 随机字符，确保唯一性
            "service": "provider-demo",       # 被调服务的服务名
            "tags": [],
            "address": "212.129.150.110", # 被调服务实例的 IP
            "port": 18081,                   # 被调服务监听端口
            "meta": {
            }
        },
        "checks": []
    }]
}

**Comment by vrongchao** [comment]
您好，TSF 官方文档提供了本地联调与本地与远程联调两种方式，本地与本地联调需要启动 provider-demo，具体可参考 [本地开发联调](https://cloud.tencent.com/document/product/649/34354) 文档。
您在使用本产品文档遇到问题时，欢迎通过通过官网页面提交反馈，还有机会获得 [腾讯云代金券礼品](https://cloud.tencent.com/developer/article/1523112)。
