### ISSUE TITLE
Something missing in DescribeImages document

### ISSUE THREAD

**Issue by athom** [tencentyun/qcloud-documents#216]
https://cloud.tencent.com/document/api/213/9418

![image](https://user-images.githubusercontent.com/85204/34336150-c8b1655e-e98f-11e7-94ab-abea28851ed4.png)

**Comment by vwruwang** [comment]
文档已更新，且该文档为旧版API，建议前往新版API查阅：https://cloud.tencent.com/document/product/213/15715
