### ISSUE TITLE
kafka.flumeBatchSize配置问题

### ISSUE THREAD

**Issue by yubobo** [tencentyun/qcloud-documents#2307]
kafka sink的配置中，
a1.sinks.k1.kafka.flumeBatchSize = 1000，还是应该 a1.sinks.k1.flumeBatchSize = 1000？

也就是说，应该是kafka.flumeBatchSize 还是 flumeBatchSize？

**Comment by vrongchao** [comment]
您好，此处使用 kafka.flumeBatchSize，示例中为正确内容，配置选项处的说明有误，已更新。
您在使用本产品文档遇到问题时，欢迎通过通过官网页面提交反馈，还有机会获得 [腾讯云代金券礼品](https://cloud.tencent.com/developer/article/1523112)。
