### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by ForBetter** [tencentyun/qcloud-documents#2476]
**qcloud-documents/product/数据库/云数据库MongoDB/操作指南/实例生命周期/连接示例/Java连接示例.md**
接入文档中

            // 读取数据
            BsonDocument filter = new BsonDocument();
            filter.append("username", new BsonString("username"));
应为

            // 读取数据
            BsonDocument filter = new BsonDocument();
            filter.append("username", new BsonString("jack"));

**Comment by vgyyuangao** [comment]
已修改
