### ISSUE TITLE
消息队列有部分文章和美团技术博客的类似

### ISSUE THREAD

**Issue by lvlvforever** [tencentyun/qcloud-documents#3541]
https://tech.meituan.com/2016/07/01/mq-design.html
这一节 消息延迟与忙等
与https://cloud.tencent.com/document/product/406/4791
中的 pull的长轮询
基本是一致的。
好尴尬

**Comment by vrongchao** [comment]
pull模式存在的问题为消息队列通用问题，我们已优化了描述，着重体现CMQ的长轮询优化方法。
