### ISSUE TITLE
上传程序包要求--stop.sh容易产生误解

### ISSUE THREAD

**Issue by zane001** [tencentyun/qcloud-documents#3730]
原文中 ps -ef|grep "python promotion"
此处的python promotion，应尽量写长一点（程序的运行进程名，包括运行参数），确保查出来的唯一，否则可能会把其他的进程也kill，导致不能start

**Comment by xurun2018** [comment]
+1

**Comment by vrongchao** [comment]
非常感谢您的反馈。考虑通用性，python promotion 暂不加长。
您在使用本产品文档遇到问题时，欢迎通过通过官网页面提交反馈，还有机会获得 [腾讯云代金券礼品](https://cloud.tencent.com/developer/article/1523112)。
