### ISSUE TITLE
服务市场的最新的那个wp博客建站

### ISSUE THREAD

**Issue by BunnySakura** [tencentyun/qcloud-documents#3854]
服务市场的最新的那个wp博客建站,宣称开机即用,重装后,就是他们的广告网站,用你的服务器打他们的广告,而且你不知道后台账号密码,进系统,mysql数据库进不了,mysql无此命令,wordpress目录也没有后台账号相关文件.简直哈批

**Comment by vxifu** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。

**Comment by vxifu** [comment]
此问题需要您 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决，会有专人对接。
给您造成不便，敬请谅解！
