### ISSUE TITLE
TIMMessageOfflinePushSettings setTitle()這個function根本不存在怎麼文檔還有= " = ?

### ISSUE THREAD

**Issue by yabee5566** [tencentyun/qcloud-documents#4071]
我用的sdk
'com.tencent.imsdk:imsdk:4.6.1'
根據你們文件
https://github.com/tencentyun/qcloud-documents/blob/master/product/%E7%A7%BB%E5%8A%A8%E4%B8%8E%E9%80%9A%E4%BF%A1/%E5%8D%B3%E6%97%B6%E9%80%9A%E4%BF%A1/7%E5%B8%B8%E8%A7%84%E9%9B%86%E6%88%90%20SDK%EF%BC%88%E6%97%A0%20UI%20%E5%BA%93%EF%BC%89/9%E7%A6%BB%E7%BA%BF%E6%8E%A8%E9%80%81/%E7%A6%BB%E7%BA%BF%E6%8E%A8%E9%80%81%EF%BC%88Android%EF%BC%89/%E7%A6%BB%E7%BA%BF%E6%8E%A8%E9%80%81%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE%EF%BC%88Android%EF%BC%89.md

我只想做個離線推送改我自定義的title，參照你們的文件叫我call setTitle()，但事實上根本沒有定義TIMMessageOfflinePushSettings setTitle(),  拜託更新一下怎麼做離線推播的教學好嗎？？？

**Comment by vcanhe** [comment]
4.6.1版本没有 TIMMessageOfflinePushSettings setTitle() 接口，该接口是4.7.2版本新增的。
旧版本可以使用 TIMMessageOfflinePushSettings > AndroidSettings > setTitle 方法
