### ISSUE TITLE
看起來這似乎沒人在維護 大家可以回家了

### ISSUE THREAD

**Issue by yabee5566** [tencentyun/qcloud-documents#4072]
就這樣 我留一個issue避免其他人誤會 還有人維護那就回一下吧 但我看之前2019年一月的文題都沒人屌 應該早廢棄了

**Comment by jaydencai** [comment]
感谢您的反馈，如果您在使用过程中发现文档存在问题，建议您登录腾讯云官网后再进行反馈，不仅可以更快了解问题处理进展，还有机会获得[腾讯云代金券礼品](https://cloud.tencent.com/developer/article/1523112)。
