### ISSUE TITLE
文档疑问

### ISSUE THREAD

**Issue by lzcgaston** [tencentyun/qcloud-documents#4144]
明明是post请求接口为什么给出来的例子是get方式的?完全搞不懂

**Comment by caicai6666** [comment]
非常感谢您的反馈，您指的是哪一篇文档？

**Comment by lzcgaston** [comment]
[cid:image002.png@01D61C78.D23329F0]

JAVA示例代码下载下来看过也是Get方式的请求,麻烦确认一下
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jayden<mailto:notifications@github.com>
发送时间: 2020年4月26日 11:04
收件人: tencentyun/qcloud-documents<mailto:qcloud-documents@noreply.github.com>
抄送: Zicheng Liu<mailto:liuzicheng124@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [tencentyun/qcloud-documents] 文档疑问 (#4144)


非常感谢您的反馈，您指的是哪一篇文档？

―

**Comment by lzcgaston** [comment]
[https://github.com/tencentyun/qcloud-documents/blob/master/product/%E9%9B%B6%E5%94%AE%E6%9C%8D%E5%8A%A1/%E8%90%A5%E9%94%80%E9%A3%8E%E6%8E%A7/API%20%E6%96%87%E6%A1%A3.md](url)

**Comment by lzcgaston** [comment]
顺便问您一下csec.api.qcloud.com这个接口在qcloud-java-sdk [https://github.com/QcloudApi/qcloudapi-sdk-java](url)  里面是找不到对应的类的,这个支持使用动态模块的方式可以进行开发吗?

**Comment by zqfan** [comment]
@lzcgaston 支持的，用最新版就可以

**Comment by sjwshi** [comment]
尊敬的腾讯云用户，您好！ 
非常感谢您的反馈，目前该接口支持 Get 和 Post 两种请求方式，JAVA 示例代码仅以 Get 方式进行举例，我们已对 [API 文档](https://github.com/tencentyun/qcloud-documents/blob/master/product/%E9%9B%B6%E5%94%AE%E6%9C%8D%E5%8A%A1/%E8%90%A5%E9%94%80%E9%A3%8E%E6%8E%A7/API%20%E6%96%87%E6%A1%A3.md) 中的描述进行了优化。
若使用中还存在其它问题，欢迎继续在官网反馈，我们收到后会尽快处理。
感谢您的支持，祝您工作顺利！
