### ISSUE TITLE
iOS 播放视频导致内存无限增长，当播放长视频内存达到某个临界点随即crash闪退

### ISSUE THREAD

**Issue by sandsame** [tencentyun/qcloud-documents#4148]
iOS 播放视频导致内存无限增长，当播放长视频内存达到某个临界点随即crash闪退

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
此问题需要您 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决，会有专人对接。
给您造成不便，敬请谅解！
