### ISSUE TITLE
我的商户是事业单位，能不能针对这部分不计费？

### ISSUE THREAD

**Issue by pqj325** [tencentyun/qcloud-documents#4214]
您好，我的商户是事业单位，支付宝微信给的费率都是0。现在的计费模式会导致每个月都有1500的费用，请问您们系统能否针对事业单位不计费呢？

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
此问题需要您 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 **95716** 解决，会有专人对接。
给您造成不便，敬请谅解！
