### ISSUE TITLE
code:InvalidParameter message:The value type of parameter `PhoneNumberSet` is not valid.

### ISSUE THREAD

**Issue by shiqishao** [tencentyun/qcloud-documents#4225]
tccli: [TencentCloudSDKException] code:InvalidParameter message:The value type of parameter `PhoneNumberSet` is not valid. requestId:fa5d98ca-64d0-4726-a57c-c74c20bf3523
这个报错应该怎么解决？
我在命令行中写的是--PhoneNumberSet  "+86133********"

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
此问题需要您 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决，会有专人对接。
给您造成不便，敬请谅解！
