### ISSUE TITLE
小程序即时通讯IM中createGroup方法未返回promise对象

### ISSUE THREAD

**Issue by jianqiao0313** [tencentyun/qcloud-documents#4241]
RT，在小程序调用createGroup的时候，未返回promise对象，而是返回了undefined，与文档例子不符,麻烦看下，谢谢。

 @caicai6666 

![企业微信截图_1588756773286](https://user-images.githubusercontent.com/15814955/81161356-0a71a680-8fbe-11ea-92ae-d931ce7b4f92.png)

![企业微信截图_1588756921862](https://user-images.githubusercontent.com/15814955/81161386-165d6880-8fbe-11ea-9d4e-2d24f076cf96.png)

**Comment by jianqiao0313** [comment]
@caicai6666

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，您的建议我们已经收到，并已提交给相应团队进行评估，我们会尽快完成评估，并给您答复，非常感谢您！

**Comment by vcanhe** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈！
经确认，[createGroup](https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html?_ga=1.148219895.1562552652.1542703643#createGroup) 需要登录后才能调用，建议您登录后重试。
如果未登录就调用该接口，SDK 会有警告日志，告警信息如下图所示：
![日志截图](https://user-images.githubusercontent.com/45193789/81250317-3d19ae80-9053-11ea-91eb-5e15aa00e921.png)
若使用中还存在其它问题，您可以 [提交工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决，会有专人对接。
感谢您的支持，祝您工作顺利！
