### ISSUE TITLE
 腾讯移动推送 > API 文档 > API (java)  android 的 badge_type，在文档中的实例中没有说明

### ISSUE THREAD

**Issue by kylin0** [tencentyun/qcloud-documents#4247]
java sdk 中 Android的badge_type 在文档的示例中为找到相关的内容，查看源代码好像也未实现相关供功能，请核对
`"android": {
        "n_ch_id": "default_message",
        "n_ch_name": "默认通知",
        "n_id": 0,
        "builder_id": 0,
        "ring": 1,
        "ring_raw": "ring",
        "vibrate": 1,
        "lights": 1,
        "clearable": 1,
        "icon_type": 0,
        "icon_res": "xg",
        "style_id": 1,
        "small_icon": "xg",
        "action": {
            "action_type": 1,// 动作类型，1，打开activity或app本身；2，打开浏览器；3，打开Intent
            "activity": "xxx",
            "aty_attr": {// activity属性，只针对action_type=1的情况
                "if": 0, // Intent的Flag属性
                "pf": 0  // PendingIntent的Flag属性
            },
            "browser": {
                "url": "xxxx ", // 仅支持http、https
                "confirm": 1 // 是否需要用户确认
            },
            "intent": "xxx" //SDK版本需要大于等于1.0.9，然后在客户端的intent配置data标签，并设置scheme属性
        },
      "custom_content":"{\"key\":\"value\"}"
    }`

**Comment by 1292169282** [comment]
我们更新一下文档，在"android"中增加"badge_type":-1, 的事例
