### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by SSStq1314** [tencentyun/qcloud-documents#4379]
文档中的组件使用前置条件，
其中创建群自定义字段
attent：记录自己关注了哪些主播

创建群成员自定义字段
add_goods ：后台上架新的直播间商品列表
room_status：控制直播间状态

这两个自定义字段是不是写反了啊，应该是这样吧，
创建群成员自定义字段
attent：记录自己关注了哪些主播

其中创建群自定义字段
add_goods ：后台上架新的直播间商品列表
room_status：控制直播间状态

还有就是我在使用过程中，小程序管理后台出现了很多报错，请问这些报错信息，我应该怎么处理，

参数非法，请检查必填字段是否填充，或者字段的填充是否满足协议要求。 construct@[native code] r@https://miniprogram:///tim-wx.js:1:1 https://miniprogram:///tim-wx.js:1:1 n@https://miniprogram:///tim-wx.js:1:1 https://miniprogram:///tim-wx.js:1:1 t@https://lib/WASubContext.js:2:65881 https://lib/WASubContext.js:2:66003 e@https://lib/WASubContext.js:2:68459 https://lib/WASubContext.js:2:32672 r@https://lib/WASubContext.js:2:32371 https://lib/WAServiceMainContext.js:2:128150 https://lib/WASubContext.js:2:93052 https://lib/WASubContext.js:2:99566

null is not an object (evaluating 'i.tls.joinRoom') at (app-service.js:7037:4984) at L (app-service.js:6613:4386) at (app-service.js:6613:4171) at asyncGeneratorStep (app-service.js:6598:58) at c (app-service.js:6598:294) at (app-service.js:6598:370) at T (WASubContext.js:2:67007) at (app-service.js:6598:228) at (app-service.js:6709:12444) at forEach (native code) at (app-service.js:6709:12422) at (app-service.js:6709:7919) at (native code) at (app-service.js:6721:317446) at (app-service.js:6721:252762) at (app-service.js:6721:327158) at (native code) at value (app-service.js:6721:329429) at (app-service.js:6721:59076) at forEach (native code) at (app-service.js:6721:59057) at (WAServiceMainContext.js:2:128150) at (WASubContext.js:2:93052) at (WASubContext.js:2:99566) _onNativeTimer global code

null is not an object (evaluating 't.tls.exitRoom');at "pages/liveRoom/index" page lifeCycleMethod onHide function at logout (app-service.js:7007:4137) at logout (native code) at onHide (app-service.js:7007:1051) at onHide (native code) at (WASubContext.js:2:1610560) at (native code) at (WASubContext.js:2:1610305) at (WASubContext.js:2:1612557) at (WASubContext.js:2:478579) at emitInternal (WASubContext.js:2:445571) at (WASubContext.js:2:485758) at (WASubContext.js:2:478579) at emit (WASubContext.js:2:445289) at (WASubContext.js:2:519056) at (WASubContext.js:2:478678) at emit (WASubContext.js:2:445289) at (WASubContext.js:2:496637) at (WASubContext.js:2:471146) at (WAServiceMainContext.js:2:242324) at A (WAServiceMainContext.js:2:77824) global code

undefined is not an object (evaluating '(e=n.sent()).code') at (app-service.js:6709:10542) at (app-service.js:6709:3053) at s (app-service.js:6709:1875) at t (WASubContext.js:2:65881) at (WASubContext.js:2:66003) at e (WASubContext.js:2:68459) at (WASubContext.js:2:32672) at r (WASubContext.js:2:32371) at (WAServiceMainContext.js:2:128150) at (WASubContext.js:2:93052) at (WASubContext.js:2:99566) _onNativeTimer global code

undefined is not an object (evaluating 's.notification') at groupInfo (pages/liveRoom/index.js:171:20) at L (app-service.js:6566:4386) at (app-service.js:6566:4171) at asyncGeneratorStep (app-service.js:6551:58) at c (app-service.js:6551:294) at t (WASubContext.js:2:65881) at (WASubContext.js:2:66003) at e (WASubContext.js:2:68459) at (WASubContext.js:2:32672) at r (WASubContext.js:2:32371) at (WAServiceMainContext.js:2:128150) at (WASubContext.js:2:93052) at (WASubContext.js:2:99566) _onNativeTimer global code

**Comment by vcanhe** [comment]
请更新至 [最新版 SDK](https://cloud.tencent.com/document/product/269/36887)。
