### ISSUE TITLE
有没有Linux 版的通讯会议？

### ISSUE THREAD

**Issue by wilfredgithuka** [tencentyun/qcloud-documents#4426]
我电脑上的系统是Linux。

希望您们能做Linux版的通讯会议，能让我们好好开会。

谢谢。

**Comment by vxifu** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验， 我们深表歉意。

**Comment by vxifu** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验， 我们深表歉意。
目前暂不支持Linux版的通讯会议，我们将持续关注并收集此类建议，再次感谢您的支持与理解！
