### ISSUE TITLE
IOS SDK Category方法与项目中冲突

### ISSUE THREAD

**Issue by jason469618528** [tencentyun/qcloud-documents#4621]
WBCloudReflectionFaceVerify.framework 
里面使用了UIButton的Category，覆盖了项目中的- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event; 

SDK应该自定义一个UIButton的子类来实现增加按钮的点击范围

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
为了能更方便、准确地定位问题，建议您在 [官网文档](https://cloud.tencent.com/document/product) 处反馈问题，以便我们尽快核实后解决！
反馈方式：
方式1：直接选中要反馈的内容，单击“文档反馈”，在弹出的界面中填写您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350656-a35c3f80-88a3-11ea-8a51-1de7f730e230.png)
方式2：单击文档页面底部反馈按钮或侧边栏的“文档反馈”提交您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350763-cb4ba300-88a3-11ea-8bc2-c3378865dd39.png)

**Comment by vyfeiyang** [comment]
下个版本优化
