### ISSUE TITLE
cosClient的关闭方法，并没有把连接关闭掉

### ISSUE THREAD

**Issue by afei199002** [tencentyun/qcloud-documents#4626]
https://github.com/tencentyun/qcloud-documents/blob/master/product/%E5%AD%98%E5%82%A8%E4%B8%8ECDN/%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%204.0/SDK%E6%96%87%E6%A1%A3/Java%20SDK/%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.md
// 关闭客户端(关闭后台线程)
cosClient.shutdown();
文档的关闭客户端的方法如上，但实际上并不会关闭连接，实际的连接依赖于PoolingHttpClientConnectionManager的finalize方法进行关闭。
finalize 方法并不一定可靠，我觉得一定情况下可能会有些问题，还是希望SDK能自己主动的去把连接关掉，而不是依赖一个可能不可靠的机制
不知道理解对不对

**Comment by liuyongqing** [comment]
非常感谢您的建议，我们会在下一个版本优化shutdown的处理过程

**Comment by vkxianli** [comment]
感谢您的建议，我们已发布新版本，优化了shutdown处理过程
