### ISSUE TITLE
SDK依赖的SDWebImage还是旧版，编译不通过啊~

### ISSUE THREAD

**Issue by NathanOu** [tencentyun/qcloud-documents#4712]
![image](https://user-images.githubusercontent.com/13098900/85936804-8f2ed000-b930-11ea-9405-9a9218fe7657.png)

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
