### ISSUE TITLE
移动端麻烦支持清晰度切换！！！

### ISSUE THREAD

**Issue by thegithubs** [tencentyun/qcloud-documents#4733]
移动端麻烦支持清晰度切换！！！

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
