### ISSUE TITLE
java.lang.UnsatisfiedLinkError:异常导致崩溃

### ISSUE THREAD

**Issue by lvTravler** [tencentyun/qcloud-documents#4788]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.ttpic.util.youtu.YTFaceDetectorBase.nativeSetRefine(boolean) (tried Java_com_tencent_ttpic_util_youtu_YTFaceDetectorBase_nativeSetRefine and Java_com_tencent_ttpic_util_youtu_YTFaceDetectorBase_nativeSetRefine__Z)

**Comment by caicai6666** [comment]
尊敬的腾讯云用户，您好！
遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
