### ISSUE TITLE
TTS javaSDK写的是啥玩意

### ISSUE THREAD

**Issue by huangjianven** [tencentyun/qcloud-documents#4834]
腾讯是不用maven吗，SDK不上传中央仓库，APPID和key竟然不是写在配置文件里，要去SDK里改，让用户去封装一道，智障吧，拿出来卖钱的东西，写成这B样，看看阿里的SDK和文档是怎么写的。

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！

**Comment by vnzxni** [comment]
尊敬的腾讯云用户，您好！
非常抱歉，目前还不支持maven，需要您自行导入。
