### ISSUE TITLE
android端识别成功后调用的activity会被重新打开

### ISSUE THREAD

**Issue by coku00** [tencentyun/qcloud-documents#4837]
android端识别成功后调用的activity会被重新打开

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
