### ISSUE TITLE
你好  pod TXIMSDK_TUIKit_iOS 的问题

### ISSUE THREAD

**Issue by jj89757hhb** [tencentyun/qcloud-documents#5017]
我pod下来后，发现ISVImageScrollView变成了swift版本？
但是之前从你们官网下载的工程看到的又是 oc版本？ 怎么解决呢？现在编译不了！

**Comment by vwwcwan** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
如果遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
