### ISSUE TITLE
关于对象存储计费

### ISSUE THREAD

**Issue by linvideo** [tencentyun/qcloud-documents#5019]
对象存储被我作为图床使用。
https://yilin.wtf/jekyll/update/2020/07/26/Day03
例如这样。
但如果我每个月用200MB流量，下行流量费用是按1GB收取还是按0.2GB收取？

**Comment by vqianvhe** [comment]
流量费用是按日结算，按使用量收取相应费用，没有最低限制的

**Comment by imlinnn** [comment]
我昨天使用了34.7MB流量，为什么没有扣费？
按日结算费用是流量*0.5（上海区标准存储）？

**Comment by vqianvhe** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验。建议您 [提工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决该问题，会有专人对接。
感谢您的支持，祝您工作顺利！
