### ISSUE TITLE
事件回调PLAY_EVT_PLAY_END

### ISSUE THREAD

**Issue by winsdom123456** [tencentyun/qcloud-documents#5247]
seekToTime方法有时会进入PLAY_EVT_PLAY_END的回调，不知道什么原因。SuperPlayerView 3.2.2版本

**Comment by vwwcwan** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
您可以 [提工单](https://console.cloud.tencent.com/workorder/category)  或致电 95716 解决，会有专人对接。
感谢您的支持，祝您工作顺利！
