### ISSUE TITLE
IMSDK android 端 直播群 群成员无需进入群就可以发消息

### ISSUE THREAD

**Issue by Quyunshuo** [tencentyun/qcloud-documents#5251]
IMSDK android 端 直播群 群成员在不进入群的情况下  只要有群id  就可以往群里发消息  此时该成员是不在群聊中的，不是群成员

**Comment by vwwcwan** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
您可以 [提工单](https://console.cloud.tencent.com/workorder/category)  或致电 95716 解决，会有专人对接。
感谢您的支持，祝您工作顺利！
