### ISSUE TITLE
接口返回状态码9042

### ISSUE THREAD

**Issue by lixhbs** [tencentyun/qcloud-documents#5264]
修改预约会议的时候，接口返回状态码9042，在文档中没有对应说明
会议没有开始。

**Comment by vlflliao1** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
经与相应团队确认，答复如下：新增9042、190001的错误码说明，可参考 [错误码](https://cloud.tencent.com/document/product/1095/43704) 。
若查看文档过程中，发现存在其它问题，欢迎继续在官网反馈，我们收到后会尽快处理。
若使用产品过程中，发现存在其它问题，请您通过 [提交工单](https://console.cloud.tencent.com/workorder/category) 或致电 95716 解决，会有专人对接。
感谢您的支持，祝您工作顺利！
