### ISSUE TITLE
服务端（Node.js）app.downloadFile超时问题

### ISSUE THREAD

**Issue by Skye-0505** [tencentyun/qcloud-documents#5309]
同样的环境和fileid,  getTempFileURL可以调通，但是downloadFile一直报超时，文件也就十几kb
![image](https://user-images.githubusercontent.com/33588563/91272727-c396ff00-e7ae-11ea-9c7f-d6b86690873c.png)
![image](https://user-images.githubusercontent.com/33588563/91272824-ee815300-e7ae-11ea-93a4-78d8341444ec.png)

**Comment by vkxianli** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
根据您提供的信息，暂时无法定位到问题。为了能更方便、准确地定位问题，还麻烦您登录腾讯云 [提交工单](https://console.cloud.tencent.com/workorder/category) 解决，我们将安排工程师与您对接。
