### ISSUE TITLE
TCWebCodesSDK.framework中使用了UIWebview，导致上架苹果商店被拒

### ISSUE THREAD

**Issue by thneng** [tencentyun/qcloud-documents#5338]
用grep -r UIWebView .命令检测到
TCWebCodesSDK.framework中使用了UIWebview，导致上架苹果商店被拒。麻烦更新一下库，去掉UIWebview的使用。

Binary file ./Pods/TCWebCodesSDK/ios/TCWebCodesSDK.framework/TCWebCodesSDK matches
./Pods/TCWebCodesSDK/ios/TCWebCodesSDK.framework/Headers/TCWebCodesBridge.h:@interface TCWebCodesBridge : NSObject <UIWebViewDelegate>

**Comment by sjwshi** [comment]
尊敬的腾讯云用户，您好！
您可以通过如下方式进行反馈：
方式1：直接选中要反馈的内容，单击“文档反馈”，在弹出的界面中填写您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350656-a35c3f80-88a3-11ea-8a51-1de7f730e230.png)
方式2：单击文档页面底部反馈按钮或侧边栏的“文档反馈”提交您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350763-cb4ba300-88a3-11ea-8bc2-c3378865dd39.png)
