### ISSUE TITLE
关于文档“qcloud-documents/product/域名与网站/网站备案/条款与公告/备案相关条款/各省管局要求.md”与事实不符

### ISSUE THREAD

**Issue by Lparksi** [tencentyun/qcloud-documents#5457]
![w0cVl4.png](https://s1.ax1x.com/2020/09/13/w0cVl4.png)
![w0cG1e.png](https://s1.ax1x.com/2020/09/13/w0cG1e.png)
希望对该部分作修改。

**Comment by vlmjlv** [comment]
已确认，文档无需调整
