### ISSUE TITLE
Web tim-js.js的polyfill污染全局变量问题

### ISSUE THREAD

**Issue by Leafykn** [tencentyun/qcloud-documents#5494]
tim-js.js本身使用的polyfill污染了全局的Promise变量，导致Angular的Zone报错（ps：在Safari上不可用），建议更改babel polyfill配置方式
![image](https://user-images.githubusercontent.com/26517379/93287352-e0ea4680-f80b-11ea-9979-75640a0bb755.png)

**Comment by vwwcwan** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，根据您提供的信息，暂时无法定位到问题。
您可以 [提工单](https://console.cloud.tencent.com/workorder/category)  或致电 95716 解决，会有专人对接。
感谢您的支持，祝您工作顺利！
