### ISSUE TITLE
请问Notebook 训练的模型，应该如何部署？

### ISSUE THREAD

**Issue by SpenserZC** [tencentyun/qcloud-documents#5695]
使用Notebook训练模型可以到模型仓库直接部署吗？
如果不行的话，又应该如何部署Notebook训练的模型呢？

**Comment by vyfeiyang** [comment]
反馈方式：
方式1：直接选中要反馈的内容，单击“文档反馈”，在弹出的界面中填写您的宝贵意见。
![](https://main.qcloudimg.com/raw/2f80a0db53ef2a9996cfb5ac99d8879c.png)
方式2：单击文档页面底部反馈按钮或侧边栏的“文档反馈”提交您的宝贵意见。
![](https://main.qcloudimg.com/raw/4e0b1e3ad6ee6c5b3b5d85d97c60e18b.png)
