### ISSUE TITLE
arm64奔溃，release奔溃，debug模式正常使用

### ISSUE THREAD

**Issue by shenyunhuan** [tencentyun/qcloud-documents#5726]
Build fingerprint: 'alps/full_rlk6580_we_c_m/rlk6580_we_c_m:7.1.1/NMF26F/472:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 9806, tid: 9842, name: .baseapi.thread  >>> com.czb.wisdomcashier:xg_vip_service <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: mid == null'
    x0   0000000000000000  x1   0000000000002672  x2   0000000000000006  x3   0000000000000008
    x4   000000000000003c  x5   0000000000000000  x6   0000000000000000  x7   feff666e6b61686b
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  00000000ffffffff  x14  000000000003c500  x15  ffffffffffffffff
    x16  0000007f920c8ed8  x17  0000007f92076750  x18  0000000000000000  x19  0000007f884fa4f8
    x20  0000000000000006  x21  0000007f884fa450  x22  000000000000000b  x23  0000007f901869d0
    x24  000000000000000a  x25  ffffffffffffffff  x26  0000000000000941  x27  0000007f884f83e1
    x28  0000007f901fc740  x29  0000007f884f82e0  x30  0000007f92073be0
    sp   0000007f884f82c0  pc   0000007f92076758  pstate 0000000060000000

**Comment by shenyunhuan** [comment]
自己版本1.2.1.1

**Comment by shenyunhuan** [comment]
自己暂时解决这个问题了，降级1.1.6.1解决问题
对了我的gradle版本是4.1.0,kotlin版本1.4.10
其他都是最新的

**Comment by vcynthia** [comment]
尊敬的腾讯云用户，您好！
如果发现产品文档问题，您可以前往 [腾讯云官网文档页面](https://cloud.tencent.com/document/product) 进行反馈。如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
