### ISSUE TITLE
IOS 使用cocopod最新版本5.0.10报错

### ISSUE THREAD

**Issue by xuzeyu** [tencentyun/qcloud-documents#5729]
TUIGroupInfoController类没引用TIMConversation+MsgExt.h类别，又调用了该类别的方法，导致报错
![7B204B76-AD56-40E8-970D-C679E1FD3C34](https://user-images.githubusercontent.com/12440908/96532728-0fea5100-12bf-11eb-9617-c555d45aa65f.png)

**Comment by vyfeiyang** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。
同时，您也可以拨打 95716 或[ 提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
