### ISSUE TITLE
ios10.1手机使用 TCapIframeApi.js不弹出验证码弹窗，也不报错

### ISSUE THREAD

**Issue by treeandgrass** [tencentyun/qcloud-documents#5745]
ios10.1手机使用 TCapIframeApi.js不弹出验证码弹窗，也不报错

其它版本的ios手机正常

**Comment by treeandgrass** [comment]
https请求验证码js，ios10.1系统 webview报 ErrorEvent {"isTrusted":true}

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [腾讯云智能客服](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
