### ISSUE TITLE
一张表可以指定多个shardkey吗

### ISSUE THREAD

**Issue by xuxinstyle** [tencentyun/qcloud-documents#5774]
由于表中有多个UNIQUE KEY,想问能不能将所有的UNIQUE都作为shardkey

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如遇到文档相关问题，您可以通过如下方式反馈：
方式1：直接选中要反馈的内容，单击“文档反馈”，在弹出的界面中填写您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350656-a35c3f80-88a3-11ea-8a51-1de7f730e230.png)
方式2：单击文档页面底部反馈按钮或侧边栏的“文档反馈”提交您的宝贵意见。
![image](https://user-images.githubusercontent.com/37574824/80350763-cb4ba300-88a3-11ea-8bc2-c3378865dd39.png)
