### ISSUE TITLE
TIME_WAIT 复用 net.ipv4.tcp_tw_reuse=1 是否会导致一些额外的问题发生？

### ISSUE THREAD

**Issue by YRM2** [tencentyun/qcloud-documents#5863]
在《Nginx Ingress 高并发实践》文章
中写道建议为 Nginx Ingress 开启 TIME_WAIT 复用，   由于TIME_WAIT被设计来可靠的关闭一个连接， 那么复用会否导致一些不可预料的网络问题？
我对网络了解不深，有些疑惑。是否可以解答一下，very谢谢。

**Comment by imroc** [comment]
> 在《Nginx Ingress 高并发实践》文章
> 中写道建议为 Nginx Ingress 开启 TIME_WAIT 复用， 由于TIME_WAIT被设计来可靠的关闭一个连接， 那么复用会否导致一些不可预料的网络问题？
> 我对网络了解不深，有些疑惑。是否可以解答一下，very谢谢。

目前没发现问题，也许在一些极端的网络条件下导致个别连接异常，但如果没开启，造成的影响更大，高并发很容易就端口耗尽，大量连接失败。
