### ISSUE TITLE
怎么正在代理下用COSCMD上传文件？

### ISSUE THREAD

**Issue by jingsong-liu** [tencentyun/qcloud-documents#6213]
怎么正在代理下上传文件？
我在公司内网，设置全局代理，无法使用COSCMD上传文件

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
