### ISSUE TITLE
白板旋转

### ISSUE THREAD

**Issue by Buried-Love** [tencentyun/qcloud-documents#6256]
希望新增,白板的canvas旋转功能.因为可能会有web端直播app端观看的情况 如果可以做到白板旋转的话 体验将会很好

**Comment by vgyyuangao** [comment]
腾讯云文档有“文档反馈”的功能，直接在文档页面就可以反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
**诚邀您参加：**
【你找茬儿，我发奖】腾讯云产品文档“捉虫”活动
检视指定产品文档，发现和反馈有效问题，将有机会获得代金券和缤纷好礼，更多大奖等你来拿哦～ 
[https://cloud.tencent.com/developer/article/1610407](https://cloud.tencent.com/developer/article/1610407)
