### ISSUE TITLE
Coscmd download不支持下载需回源的文件

### ISSUE THREAD

**Issue by harryzyzhao** [tencentyun/qcloud-documents#6333]
coscmd download xxxxx   ./

内部逻辑是先head在download， head不触发回源，因找不到文件报错
message': 'The Resource You Head Not Exist', 'code': 'NoSuchResource',

**Comment by vwruwang** [comment]
根据您提供的信息，暂时无法定位到问题。建议您咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。

**Comment by vwruwang** [comment]
根据您提供的信息，暂时无法定位到问题。建议您咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
