### ISSUE TITLE
图形验证码在iOS平台上使用了UIWebView导致上架被拒

### ISSUE THREAD

**Issue by guolingege** [tencentyun/qcloud-documents#6698]
涉及该代码的文件是TCWebCodesSDK/TCWebCodesSDK

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [在线客服 ](https://cloud.tencent.com/act/event/smarty-service?from=connect-offical)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
