### ISSUE TITLE
多人视频会议的时候俩个人的显示 可不可以左右对称，不使用上下

### ISSUE THREAD

**Issue by donghang54321** [tencentyun/qcloud-documents#6770]

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
