### ISSUE TITLE
文档小细节：手动搭建LNMP环境（CentOS8）.md

### ISSUE THREAD

**Issue by lukelhi** [tencentyun/qcloud-documents#6778]
![QQ截图20210305225030](https://user-images.githubusercontent.com/50158538/110131690-633fe480-7e05-11eb-9a0a-d45a2a4dcb13.png)

命令执行之后：

![QQ截图20210305224848](https://user-images.githubusercontent.com/50158538/110131342-03493e00-7e05-11eb-8b95-3204e419275f.png)

建议在第四步之前添加：查看初始化密码的步骤代码。
新手看到让输入密码，会很懵，导致初始密码不成功。

**Comment by vyixzheng** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
文档中提供的 MySQL 安全性操作及密码设置步骤，是以首次安装 MySQL 为例。
经过综合评估后，您的建议暂未被采纳。再次感谢您的支持与关注，期待提出更多建议！
