### ISSUE TITLE
视图和自定义函数支持

### ISSUE THREAD

**Issue by maocw** [tencentyun/qcloud-documents#6818]
大特性限制
不支持自定义函数、事件、表空间
不支持视图、存储过程、触发器、游标
--------------------------------------------------
为什么使用过程中可以正常使用视图和自定义函数，
是否有什么前提条件下不支持函数和视图

**Comment by Sean-Zheng** [comment]
同样的疑问，视图和存储过程都可以使用，为什么文档写不可以？

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
分布式数据库不支持自定义函数、视图、存储。请确认您使用的是否为分布式数据库。
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面就可以反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
