### ISSUE TITLE
vue 项目 引入媒体上传sdk 的js文件后白屏

### ISSUE THREAD

**Issue by hiblueboy** [tencentyun/qcloud-documents#6829]
vue 项目 引入媒体上传 import TcVod from 'vod-js-sdk-v6' 后白屏

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面就可以反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
