### ISSUE TITLE
你们在Nuget上不支持.net 4.5的？

### ISSUE THREAD

**Issue by phoenix1630** [tencentyun/qcloud-documents#6890]
拜托，今年2021年了。

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
