### ISSUE TITLE
云API大驼峰与Java Bean代码规范冲突问题

### ISSUE THREAD

**Issue by 346673164** [tencentyun/qcloud-documents#6999]
看代码是通过Gson去处理。在请求的时候，代码 AbstractModel.java:111中AbstractModel.toJsonObject使用了反射调用字段，这时候如果字段大小驼峰不一致，会出现错误。
这里使用了 e.printStackTrace(); 但是不影响整个业务，但是这快代码是否考虑进行优化。

**Comment by zqfan** [comment]
这个异常捕获如注释所说，不应该发生。麻烦给一下具体是哪个接口遇到这个问题了
