### ISSUE TITLE
文档中对组件的介绍内容在哪里？没有找到相关的介绍

### ISSUE THREAD

**Issue by WangXin008** [tencentyun/qcloud-documents#7130]
我想知道每个组件是实现什么功能，以及如何对每个组件进行配置。
![image](https://user-images.githubusercontent.com/42570642/115701081-fa530280-a399-11eb-8a59-5ca79ca5a3c0.png)

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
