### ISSUE TITLE
前端打包后的静态资源放在腾讯云，网页加载腾讯云资源不走gizp

### ISSUE THREAD

**Issue by xianxiango** [tencentyun/qcloud-documents#7161]
为什么我vue前端代码打包后的静态文件放到腾讯云之后请求腾讯云上的所有文件都不能gzip压缩，nginx都配好了，也生成gz文件放在腾讯云了。但是直接读取本地静态资源的时候又会gzip压缩。

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
