### ISSUE TITLE
直接在文档中标注“解封”逻辑合适吗？

### ISSUE THREAD

**Issue by wangzi0218** [tencentyun/qcloud-documents#7363]
![image](https://user-images.githubusercontent.com/7765857/118427207-4118eb80-b6ff-11eb-80cf-1e4e1d3f918a.png)
![image](https://user-images.githubusercontent.com/7765857/118427248-555ce880-b6ff-11eb-9ede-f473ebcfea5f.png)
![image](https://user-images.githubusercontent.com/7765857/118427260-5ee65080-b6ff-11eb-9c75-189d18b1742b.png)
理解起来会觉得直接收保护费吗？

**Comment by xiaoxiama** [comment]
已更新文档
