### ISSUE TITLE
请确认“latest”拼写，多处写为“lateast”，部分镜像  tag 同样有错误

### ISSUE THREAD

**Issue by RogerHao** [tencentyun/qcloud-documents#739]
最佳实践-创建简单web应用中，多个 latest 写成了   lateast，且实际镜像中tag中，包含lateast和latest。其中 frontend 镜像中无 latest ，只有 lateast。用户可能会默认输入 latest，造成镜像拉取失败。

https://cloud.tencent.com/document/product/457/6996

**Comment by vyixzheng** [comment]
1. 文档中无 lateast 误写。
2. 经验证，frontend 版本为 latest 无误。
关闭此 issue。
