### ISSUE TITLE
uniapp H5环境下使用 tim-upload-plugin 上传图片报错

### ISSUE THREAD

**Issue by haoxf** [tencentyun/qcloud-documents#7573]
报错信息如下：

UploadModule._uploadWithPreSigUrl failed, error: {"errMsg":"uploadFile:fail parameter `filePath`. Expected String with value \"[object File]\", got File "}

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
