### ISSUE TITLE
 短视频SDK自动获取网上最新版本报错了，运行不了

### ISSUE THREAD

**Issue by baigao2015** [tencentyun/qcloud-documents#7765]
supportUgcLibraryAarVersion = "com.tencent.liteav:LiteAVSDK_UGC:latest.release"   // 自动获取网上最新版本

## 问题：
Execution failed for task ':library:beautysettingkit:javaPreCompileDebug'.
> Could not resolve all files for configuration ':library:beautysettingkit:debugCompileClasspath'.
   > Could not find LiteAVSDK_UGC.jar (com.tencent.liteav:LiteAVSDK_UGC:8.8.10254).
     Searched in the following locations:
         https://maven.aliyun.com/repository/central/com/tencent/liteav/LiteAVSDK_UGC/8.8.10254/LiteAVSDK_UGC-8.8.10254.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，这个问题是偶发还是必现呢
可以提供下build.gradle 相关信息 ，方便进一步定位问题 
技术问题 欢迎交流 q2562367945 注明来意

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，这个问题是偶发还是必现呢
可以提供下build.gradle 相关信息 ，方便进一步定位问题
技术问题 欢迎交流 q2562367495  注明来意

**Comment by CQBOBOZHU** [comment]
![image](https://user-images.githubusercontent.com/20177774/123386545-5e2bbe80-d5c9-11eb-9a8f-daf8f0deff74.png)
groupid搞错了吧。
最新的得 implementation 'com.tencent.liteav:LiteAVSDK_Professional:8.8.10254'  这样去拉去了。

**Comment by baigao2015** [comment]
> 您好，根据您的问题，这个问题是偶发还是必现呢
> 可以提供下build.gradle 相关信息 ，方便进一步定位问题
> 技术问题 欢迎交流 q2562367495 注明来意

问题是升级8.xxxx后就一直报错，后面只能改成固定版本号才解决。

#### 工程build.gradle 配置相关信息
```
ext {
    // SDK And Tools
    minSdkVersion =17
    targetSdkVersion = 26
    compileSdkVersion = 30
    //Dependencies
    supportLibraryVersion = '28.0.0'

    // ugc aar 包版本
    supportUgcLibraryAarVersion = "com.tencent.liteav:LiteAVSDK_UGC:latest.release"   // 自动获取网上最新版本
}
```


#### 工程app下build.gradle 配置ugc相关信息

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // 其他 implementation ......

    implementation rootProject.supportUgcLibraryAarVersion    // ugc包
}
```
