### ISSUE TITLE
 COSObject cosObject = cosClient.getObject(getObjectRequest) Last_Modified ERROR!

### ISSUE THREAD

**Issue by zhzwl99** [tencentyun/qcloud-documents#8059]
COSObject cosObject = cosClient.getObject(getObjectRequest);

cosObject.getObjectMetadata().getLastModified(). ERROR!
时间转化的不对

**Comment by vwruwang** [comment]
如果遇到产品使用等相关问题，您可以通过 [联系我们](https://cloud.tencent.com/document/product/436/37708) 来寻求帮助。
