### ISSUE TITLE
这里是不是有点不合理

### ISSUE THREAD

**Issue by Davidzhu001** [tencentyun/qcloud-documents#8113]
![image](https://user-images.githubusercontent.com/9436230/125189072-0186ff80-e269-11eb-9962-584477437174.png)

**Comment by v-guanhuang** [comment]
这个 GroupID 和 Name 是哪里不合理，参数还是？鉴于开发环境不同和问题分析的需要，为了快速解决您的问题，您可通过 https://console.cloud.tencent.com/workorder/category 或致电 4009100100 解决，会有专人对接。
