### ISSUE TITLE
tim-js-sdk支持websocket

### ISSUE THREAD

**Issue by ppny** [tencentyun/qcloud-documents#8156]
tim-js-sdk从2.7升级到了2.12为什么还是采用轮询，不断的发请求呢？有其他的地方要改动嘛

**Comment by v-guanhuang** [comment]
您可以改用 tim-upload-plugin，上传文件速度较 cos-js-sdk 和 cos-wx-sdk 快10%~50%，文档：https://cloud.tencent.com/document/product/269/52962
