### ISSUE TITLE
文档缺失

### ISSUE THREAD

**Issue by abearxiong** [tencentyun/qcloud-documents#8200]
[CloudBase Error]
CloudBaseError: [UpdateFunctionIncrementalCode] Files取值与规范不符，请修正后再试。可参考：https://mc.tencent.com/dcPGxe15

[云开发文档](https://cloud.tencent.com/document/product/583/55008)

缺少Files取值不规范的原因

**Comment by WilsonLiu95** [comment]
这边是使用什么工具过程中遇到这个错误呢？请提供更多信息以便我们定位到问题

**Comment by abearxiong** [comment]
额，好久前了，用vscode干嘛来着。那句话里面中：缺少Files取值不规范的原因之上，都是那个工具的报错。

但是我在文档里面没找到是因为啥。

**Comment by abearxiong** [comment]
![image](https://user-images.githubusercontent.com/23001129/128821254-25a8f51d-3119-4513-96d5-f4082511f1f3.png)
不常见错误，，，，咋办🤔
