### ISSUE TITLE
TCPlayerLite在横屏后变成竖屏后浏览器图标底部会被挡住

### ISSUE THREAD

**Issue by HuangGuoY** [tencentyun/qcloud-documents#8419]
机型 Iphone6s
浏览器Safari
IOS版本12.5.2
![image](https://user-images.githubusercontent.com/28726714/128113719-6aea74b7-86a3-4ca6-b38c-63348ab20164.png)

**Comment by vyunyilin** [comment]
尊敬的腾讯云用户，您好！
非常抱歉给您带来不好的体验，我们深表歉意。
此问题需要您提交工单（https://console.cloud.tencent.com/workorder/category） 或致电 4009100100 解决，会有专人对接。
给您造成不便，敬请谅解！
