### ISSUE TITLE
域名注册商资质升级问题

### ISSUE THREAD

**Issue by hayye** [tencentyun/qcloud-documents#8508]
意思是不是之前注册的域名是腾讯代理新网的，实际域名由新提供；
而现在腾讯也有域名资质，如果升级后，域名实际注册商就是腾讯？
我的问题是，我为什么要升级？如果不升级有什么影响？升级了又有什么好处？

**Comment by vlmjlv** [comment]
原新网资质域名为腾讯代理资质，提供的产品服务受制于新网约束。
升级为腾讯云自有域名注册资质后，可提供腾讯云更完善的产品能力，无论是功能特性、价格都更具自主性。因此建议客户升级域名注册商服务
