### ISSUE TITLE
自定义时间监听返回的Message operationType 字段没有？ 那前端这么判断这个消息是干嘛的 

### ISSUE THREAD

**Issue by zqxb** [tencentyun/qcloud-documents#8580]

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
