### ISSUE TITLE
平台提供的聚类算法支持分布式吗？

### ISSUE THREAD

**Issue by zxgm** [tencentyun/qcloud-documents#8808]
平台提供k-means，高斯混合模型以及二分K均值聚类算法是分布式的吗？若是分布式算法，基于spark的实现？如果是基于spark的实现，有提供配置硬件资源的接口吗？

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
