### ISSUE TITLE
华为Android10 native崩溃

### ISSUE THREAD

**Issue by hy-liuyuzhe** [tencentyun/qcloud-documents#9364]
是否Root：否

地域：中国贵州省贵阳市

机型版本：BMH-AN20

设备电量：67

电池温度：310

渠道信息：huawei

磁盘可用占比：33.3

内存可用占比：2.02

SD卡可用占比：--

CPU架构：arm64-v8a,armeabi-v7a,armeabi

umid：5fb10b6c9b7f092081a725959b2a38

使用时长（s）：2602.00

前后台状态：前台

网络类型：unknown

Process Name: 'com.ymatou.shop'
Thread Name: 'RenderThread'
pid: 4853, tid: 5103  >>> com.ymatou.shop <<<
killed by pid: 4853, comm: com.ymatou.shop, uid: 10245.
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
  r0 00000000  r1 000013ef  r2 00000006  r3 a7517738
  r4 a751774c  r5 a7517730  r6 000012f5  r7 0000016b
  r8 a7517748  r9 a7517738  10 a7517768  fp a7517758
  ip 000013ef  sp a7517708  lr e689f4ef  pc e689f502  cpsr 00870030
  d0  0000000000000000  d1  0000021e00000015
  d2  0000051400000000  d3  0000000000000008
  d4  0000000000000000  d5  0000000000000000
  d6  0000000000000000  d7  0000000000000000
  d8  0000000000000000  d9  0000000000000000
  d10 0000000000000000  d11 0000000000000000
  d12 0000000000000000  d13 0000000000000000
  d14 0000000000000000  d15 0000000000000000
  d16 00000009e46d1570  d17 00000001f27bdddb
  d18 00000001328212bf  d19 00000000bff9cb1c
  d20 0000000000000000  d21 0000000014fff262
  d22 0000000000fffdd6  d23 0000000000ffff5a
  d24 0000000000ffffeb  d25 0000000001000000
  d26 000000000000021e  d27 0000000000000070
  d28 000000021dffd38a  d29 0000000070000000
  d30 000008b000000757  d31 0000098300000c0e
  scr 20000013

    #00  pc 0002a502  /apex/com.android.runtime/lib/bionic/libc.so (abort)
    #01  pc 002be6c2  /apex/com.android.runtime/lib/libart.so (_ZN3art7Runtime5AbortEPKc)
    #02  pc 000025e0  libbase.so (_ZN7android4base10LogMessageD2Ev)
    #03  pc 00009c98  libui.so (_ZN7android19GraphicBufferMapper27importBufferMaintenanceInfoEi)
    #04  pc 00009d82  libui.so (_ZN7android19GraphicBufferMapper12importBufferEPK13native_handlejjjiyjPS3_)
    #05  pc 0000864c  libui.so (_ZN7android13GraphicBuffer9unflattenERPKvRjRPKiS4_)
    #06  pc 0007afbe  libandroid_runtime.so
    #07  pc 00014edc  libbinder.so (_ZNK7android6Parcel4readERNS0_26FlattenableHelperInterfaceE)
    #08  pc 00014f66  libgui.so
    #09  pc 0003ff18  libgui.so (_ZN7android7Surface13dequeueBufferEPP19ANativeWindowBufferPi)
    #10  pc 0017947c  libhwui.so
    #11  pc 011b3c50  /vendor/lib/egl/libGLES_mali.so
    #12  pc 011c16c8  /vendor/lib/egl/libGLES_mali.so
    #13  pc 011c14a6  /vendor/lib/egl/libGLES_mali.so
    #14  pc 011bef48  /vendor/lib/egl/libGLES_mali.so
    #15  pc 000086e2  libEGL.so
    #16  pc 00006c82  libhwui.so
    #17  pc 00003cac  libhwui.so
    #18  pc 00152962  libhwui.so
    #19  pc 001520c4  libhwui.so
    #20  pc 001591da  libhwui.so
    #21  pc 00159032  libhwui.so
    #22  pc 00003912  libutils.so (_ZN7android6Thread11_threadLoopEPv)
    #23  pc 00072546  /apex/com.android.runtime/lib/bionic/libc.so (_ZL15__pthread_startPv)
    #24  pc 0002b9f6  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread)
    --- --- ---
    00 pc 0002a502  /apex/com.android.runtime/lib/bionic/libc.so (abort+165)
    01 pc 002be6c1  /apex/com.android.runtime/lib/libart.so (_ZN3art7Runtime5AbortEPKc+1980)
    02 pc 000025e1  libbase.so (_ZN7android4base10LogMessageD2Ev+488)
    03 pc 00009c97  libui.so (_ZN7android19GraphicBufferMapper27importBufferMaintenanceInfoEi+234)
    04 pc 00009d81  libui.so (_ZN7android19GraphicBufferMapper12importBufferEPK13native_handlejjjiyjPS3_+100)
    05 pc 0000864b  libui.so (_ZN7android13GraphicBuffer9unflattenERPKvRjRPKiS4_+530)
    06 pc 0007afbd  libandroid_runtime.so
    07 pc 00014edd  libbinder.so (_ZNK7android6Parcel4readERNS0_26FlattenableHelperInterfaceE+340)
    08 pc 00014f65  libgui.so
    09 pc 0003ff19  libgui.so (_ZN7android7Surface13dequeueBufferEPP19ANativeWindowBufferPi+712)
    10 pc 0017947d  libhwui.so
    11 pc 011b3c51  /vendor/lib/egl/libGLES_mali.so
    --- --- --- ---

memory near r1:
    000013ec -------- -------- -------- --------  ................

memory near r3:
    a75176f8 00000001 a7517730 000012f5 a7517810  ....0wQ......xQ.
    a7517708 a7517778 a7517788 a7517798 a75177a8  xwQ..wQ..wQ..wQ.
    a7517718 00000000 e687ac77 00000000 00000000  ....w...........
    a7517728 e70d6000 87e00000 ffffffdf ffffffff  .`..............
    a7517738 00000000 00000000 ffffffff 000012f5  ................
    a7517748 00002805 00000000 00000000 00000000  .(..............
    a7517758 00000000 00000000 00000000 00000000  ................
    a7517768 00000000 00000000 00000000 00000000  ................
    a7517778 00000000 00000000 00000000 00000000  ................
    a7517788 00000000 00000000 00000000 00000000  ................
    a7517798 00000000 00000000 00000000 00000000  ................
    a75177a8 00000000 00000000 00000000 00000000  ................
    a75177b8 00000000 00000000 00000000 00000000  ................
    a75177c8 d44e8786 00000001 af7bcd30 e4a35714  ..N.....0.{..W..
    a75177d8 a7517810 00000006 a7518490 a7517930  .xQ.......Q.0yQ.
    a75177e8 e966bee0 e495a6c5 00000005 00000000  ..f.............

memory near r4:
    a751770c a7517788 a7517798 a75177a8 00000000  .wQ..wQ..wQ.....
    a751771c e687ac77 00000000 00000000 e70d6000  w............`..
    a751772c 87e00000 ffffffdf ffffffff 00000000  ................
    a751773c 00000000 ffffffff 000012f5 00002805  .............(..
    a751774c 00000000 00000000 00000000 00000000  ................
    a751775c 00000000 00000000 00000000 00000000  ................
    a751776c 00000000 00000000 00000000 00000000  ................
    a751777c 00000000 00000000 00000000 00000000  ................
    a751778c 00000000 00000000 00000000 00000000  ................
    a751779c 00000000 00000000 00000000 00000000  ................
    a75177ac 00000000 00000000 00000000 00000000  ................
    a75177bc 00000000 00000000 00000000 d44e8786  ..............N.
    a75177cc 00000001 af7bcd30 e4a35714 a7517810  ....0.{..W...xQ.
    a75177dc 00000006 a7518490 a7517930 e966bee0  ......Q.0yQ...f.
    a75177ec e495a6c5 00000005 00000000 ffffffff  ................
    a75177fc 0000003d a1e46520 0000000c a1e46520  =... e...... e..

memory near r5:
    a75176f0 00000001 a7517730 00000001 a7517730  ....0wQ.....0wQ.
    a7517700 000012f5 a7517810 a7517778 a7517788  .....xQ.xwQ..wQ.
    a7517710 a7517798 a75177a8 00000000 e687ac77  .wQ..wQ.....w...
    a7517720 00000000 00000000 e70d6000 87e00000  .........`......
    a7517730 ffffffdf ffffffff 00000000 00000000  ................
    a7517740 ffffffff 000012f5 00002805 00000000  .........(......
    a7517750 00000000 00000000 00000000 00000000  ................
    a7517760 00000000 00000000 00000000 00000000  ................
    a7517770 00000000 00000000 00000000 00000000  ................
    a7517780 00000000 00000000 00000000 00000000  ................
    a7517790 00000000 00000000 00000000 00000000  ................
    a75177a0 00000000 00000000 00000000 00000000  ................
    a75177b0 00000000 00000000 00000000 00000000  ................
    a75177c0 00000000 00000000 d44e8786 00000001  ..........N.....
    a75177d0 af7bcd30 e4a35714 a7517810 00000006  0.{..W...xQ.....
    a75177e0 a7518490 a7517930 e966bee0 e495a6c5  ..Q.0yQ...f.....

memory near r6:
    000012f4 -------- -------- -------- --------  ................

memory near r8:
    a7517708 a7517778 a7517788 a7517798 a75177a8  xwQ..wQ..wQ..wQ.
    a7517718 00000000 e687ac77 00000000 00000000  ....w...........
    a7517728 e70d6000 87e00000 ffffffdf ffffffff  .`..............
    a7517738 00000000 00000000 ffffffff 000012f5  ................
    a7517748 00002805 00000000 00000000 00000000  .(..............
    a7517758 00000000 00000000 00000000 00000000  ................
    a7517768 00000000 00000000 00000000 00000000  ................
    a7517778 00000000 00000000 00000000 00000000  ................
    a7517788 00000000 00000000 00000000 00000000  ................
    a7517798 00000000 00000000 00000000 00000000  ................
    a75177a8 00000000 00000000 00000000 00000000  ................
    a75177b8 00000000 00000000 00000000 00000000  ................
    a75177c8 d44e8786 00000001 af7bcd30 e4a35714  ..N.....0.{..W..
    a75177d8 a7517810 00000006 a7518490 a7517930  .xQ.......Q.0yQ.
    a75177e8 e966bee0 e495a6c5 00000005 00000000  ..f.............
    a75177f8 ffffffff 0000003d a1e46520 0000000c  ....=... e......

memory near r9:
    a75176f8 00000001 a7517730 000012f5 a7517810  ....0wQ......xQ.
    a7517708 a7517778 a7517788 a7517798 a75177a8  xwQ..wQ..wQ..wQ.
    a7517718 00000000 e687ac77 00000000 00000000  ....w...........
    a7517728 e70d6000 87e00000 ffffffdf ffffffff  .`..............
    a7517738 00000000 00000000 ffffffff 000012f5  ................
    a7517748 00002805 00000000 00000000 00000000  .(..............
    a7517758 00000000 00000000 00000000 00000000  ................
    a7517768 00000000 00000000 00000000 00000000  ................
    a7517778 00000000 00000000 00000000 00000000  ................
    a7517788 00000000 00000000 00000000 00000000  ................
    a7517798 00000000 00000000 00000000 00000000  ................
    a75177a8 00000000 00000000 00000000 00000000  ................
    a75177b8 00000000 00000000 00000000 00000000  ................
    a75177c8 d44e8786 00000001 af7bcd30 e4a35714  ..N.....0.{..W..
    a75177d8 a7517810 00000006 a7518490 a7517930  .xQ.......Q.0yQ.
    a75177e8 e966bee0 e495a6c5 00000005 00000000  ..f.............

memory near sl:
    a7517728 e70d6000 87e00000 ffffffdf ffffffff  .`..............
    a7517738 00000000 00000000 ffffffff 000012f5  ................
    a7517748 00002805 00000000 00000000 00000000  .(..............
    a7517758 00000000 00000000 00000000 00000000  ................
    a7517768 00000000 00000000 00000000 00000000  ................
    a7517778 00000000 00000000 00000000 00000000  ................
    a7517788 00000000 00000000 00000000 00000000  ................
    a7517798 00000000 00000000 00000000 00000000  ................
    a75177a8 00000000 00000000 00000000 00000000  ................
    a75177b8 00000000 00000000 00000000 00000000  ................
    a75177c8 d44e8786 00000001 af7bcd30 e4a35714  ..N.....0.{..W..
    a75177d8 a7517810 00000006 a7518490 a7517930  .xQ.......Q.0yQ.
    a75177e8 e966bee0 e495a6c5 00000005 00000000  ..f.............
    a75177f8 ffffffff 0000003d a1e46520 0000000c  ....=... e......
    a7517808 a1e46520 00000000 00000021 0000000c   e......!.......
    a7517818 923b7f80 e68f617c a1e46520 e5892616  ..;.|a.. e...&..

memory near fp:
    a7517718 00000000 e687ac77 00000000 00000000  ....w...........
    a7517728 e70d6000 87e00000 ffffffdf ffffffff  .`..............
    a7517738 00000000 00000000 ffffffff 000012f5  ................
    a7517748 00002805 00000000 00000000 00000000  .(..............
    a7517758 00000000 00000000 00000000 00000000  ................
    a7517768 00000000 00000000 00000000 00000000  ................
    a7517778 00000000 00000000 00000000 00000000  ................
    a7517788 00000000 00000000 00000000 00000000  ................
    a7517798 00000000 00000000 00000000 00000000  ................
    a75177a8 00000000 00000000 00000000 00000000  ................
    a75177b8 00000000 00000000 00000000 00000000  ................
    a75177c8 d44e8786 00000001 af7bcd30 e4a35714  ..N.....0.{..W..
    a75177d8 a7517810 00000006 a7518490 a7517930  .xQ.......Q.0yQ.
    a75177e8 e966bee0 e495a6c5 00000005 00000000  ..f.............
    a75177f8 ffffffff 0000003d a1e46520 0000000c  ....=... e......
    a7517808 a1e46520 00000000 00000021 0000000c   e......!.......

memory near ip:
    000013ec -------- -------- -------- --------  ................

code around pc:
    e689f4c0 f1098acf 90000040 0810f109 8acff900  ....@...........
    e689f4d0 f9042014 f04f8ac0 f90a30ff f90b8acf  . ....O..0......
    e689f4e0 f9088acf 960f8acf f04f900e 2100ea52  ..........O.R..!
    e689f4f0 60212206 90104639 464b4630 176bf240  ."!`9F..0FKF@.k.
    e689f500 a904df00 460a4821 f9604478 68000acd  ....!H.FxD`....h
    e689f510 0acdf942 20066010 f04f2200 2002ec72  B....`. ."O.r.. 
    e689f520 22004629 ebb4f04f f04f2014 4605ebc2  )F."O.... O....F
    e689f530 f04f20e0 4606ebbe 464c9803 8acff90a  . O....F..LF....
    e689f540 8acff90b 8acff900 f9089802 f9008acf  ................
    e689f550 98018acf 8acff900 f9009800 20148acf  ............... 
    e689f560 8ac0f904 30fff04f 900e950f ea10f04f  ....O..0....O...
    e689f570 22062100 46316021 46289010 f240464b  .!."!`1F..(FKF@.
    e689f580 df00176b f04f207f bf00ec44 fffceb2c  k.... O.D...,...
    e689f590 f04e2300 d4d4bc89 4c03b510 f8d4447c  .#N........L|D..
    e689f5a0 e8bdc000 47604010 00051c20 4601460a  .....@`G ....F.F
    e689f5b0 0063f06f f04e2300 d4d4bc7d b082b510  o.c..#N.}.......

code around lr:
    e689f4ac 0a30f109 8acff900 0050f109 f1099001  ..0.......P.....
    e689f4bc f9000b20 f1098acf 90000040 0810f109   .......@.......
    e689f4cc 8acff900 f9042014 f04f8ac0 f90a30ff  ..... ....O..0..
    e689f4dc f90b8acf f9088acf 960f8acf f04f900e  ..............O.
    e689f4ec 2100ea52 60212206 90104639 464b4630  R..!."!`9F..0FKF
    e689f4fc 176bf240 a904df00 460a4821 f9604478  @.k.....!H.FxD`.
    e689f50c 68000acd 0acdf942 20066010 f04f2200  ...hB....`. ."O.
    e689f51c 2002ec72 22004629 ebb4f04f f04f2014  r.. )F."O.... O.
    e689f52c 4605ebc2 f04f20e0 4606ebbe 464c9803  ...F. O....F..LF
    e689f53c 8acff90a 8acff90b 8acff900 f9089802  ................
    e689f54c f9008acf 98018acf 8acff900 f9009800  ................
    e689f55c 20148acf 8ac0f904 30fff04f 900e950f  ... ....O..0....
    e689f56c ea10f04f 22062100 46316021 46289010  O....!."!`1F..(F
    e689f57c f240464b df00176b f04f207f bf00ec44  KF@.k.... O.D...
    e689f58c fffceb2c f04e2300 d4d4bc89 4c03b510  ,....#N........L
    e689f59c f8d4447c e8bdc000 47604010 00051c20  |D.......@`G ...

stack:
    a75176c8:  00000002 e68f617c 00000000 a7518490 
    a75176d8:  a7517930 b7050a27 e68fdc4c b75a5708 
    a75176e8:  dbfec66d d44e8786 00000001 a7517730 
    a75176f8:  00000001 a7517730 000012f5 a7517810 
    a7517708:  a7517778 a7517788 a7517798 a75177a8   #sp
    a7517718:  00000000 e687ac77 00000000 00000000 
    a7517728:  e70d6000 87e00000 ffffffdf ffffffff 
    a7517738:  00000000 00000000 ffffffff 000012f5 
    a7517748:  00002805 00000000 00000000 00000000 
    a7517758:  00000000 00000000 00000000 00000000 
    a7517768:  00000000 00000000 00000000 00000000 
    a7517778:  00000000 00000000 00000000 00000000 
    a7517788:  00000000 00000000 00000000 00000000 
    a7517798:  00000000 00000000 00000000 00000000 
    a75177a8:  00000000 00000000 00000000 00000000 
    a75177b8:  00000000 00000000 00000000 00000000 
    a75177c8:  d44e8786 00000001 af7bcd30 e4a35714 
    a75177d8:  a7517810 00000006 a7518490 a7517930 
    a75177e8:  e966bee0 e495a6c5 00000005 00000000 
    a75177f8:  ffffffff 0000003d a1e46520 0000000c 
    a7517808:  a1e46520 00000000 00000021 0000000c 
    a7517818:  923b7f80 e68f617c a1e46520 e5892616 
    a7517828:  80000000 a7517930 a7518490 a7517930 
    a7517838:  e4afd044 e70ce5e3 e5892616 a1e46520 
    a7517848:  b29b3e00 e9618b78 000012f5 e68f617c 
    a7517858:  00000031 00000024 a1e46520 a1e46520 
    a7517868:  d44e8786 a75178a0 b29b3e00 9e3ff000 
    a7517878:  e68f617c a7517930 a7518490 0000000c 
    a7517888:  e4afd044 e589dc9b 00000006 e5892616 
    a7517898:  ffffffff 00000000 00000021 00000013 
    a75178a8:  9e3ff000 00000000 00000000 00000000 
    a75178b8:  00000000 9177e040 9b183000 e4e7d4e1 
    a75178c8:  00000000 e68f617c 00000000 a7518110 
    a75178d8:  00000000 e4e7e46b a7517990 00000000 
    a75178e8:  a7517950 9177e080 a7517f9c 94d79000 
    a75178f8:  9177e040 a2e2af00 00000000 94d79000 
    a7517908:  00000000 00000000 00000000 00000000 
    a7517918:  00000000 00000000 00000000 00000000 
    a7517928:  00000000 00000000 b29b3e00 00000000 
    a7517938:  00000000 00000000 00000000 00000000 
    a7517948:  3f800000 00000000 00000000 00000000 
    a7517958:  00000000 3f800000 00000000 00000000 
    a7517968:  00000000 00000000 3f800000 00000000 
    a7517978:  00000000 00000000 00000000 3f800000 
    a7517988:  00000010 a7517a80 e68f6100 e95310ac 
    a7517998:  e95310c4 0000000e 00000000 00a1e000 
    a75179a8:  00000000 e68ab31f 0000014e 00000000 
    a75179b8:  b9d1eb00 00a1e000 000012f5 a7517a08 
    a75179c8:  951ac728 d44e8786 0000014e 00a1e000 
    a75179d8:  d44e8786 a7518490 00000000 b9d1eb00 
    a75179e8:  b75a5700 b75a5708 e68f6114 a7517ad0 
    a75179f8:  e68f617c e688c3a7 000012f5 a7517a38 
    a7517a08:  a7518490 b9d1eb14 0000000c d44e8786 
    a7517a18:  a7517a70 00000002 b9d1eb00 a7517a60 
    a7517a28:  a7517ad0 e68f617c 00000000 caa698e5 
    a7517a38:  a7517a60 946da4bf a7517b10 00000000 
    a7517a48:  a7517ac0 e8432063 00000000 00000002 
    a7517a58:  d44e8786 a7517ab8 00000000 00000000 
    a7517a68:  00000000 00000000 00000000 00000000 
    a7517a78:  d44e8786 a7517b10 d44e8786 a7517b10 
    a7517a88:  a7517ab8 a7517b78 cab340e9 a7517aa0 
    a7517a98:  e68f617c e8191d8d 00000000 00000000 
    a7517aa8:  00000000 00000000 00000000 ac1e7000 
    a7517ab8:  00000000 00000000 00000000 00000000 
    a7517ac8:  00000000 d44e8701 e8196a00 a7517b28 
    a7517ad8:  ba396ba0 ba396d58 a7517ad0 a7517c68 
    a7517ae8:  d44e8786 00000002 00000000 e68f617c 
    a7517af8:  a7517b78 e4afa018 00000438 e589a0f1 
    a7517b08:  00000002 a7517b74 00000000 00000000 
    a7517b18:  00000000 00000000 00000000 e5489801 
    a7517b28:  e58a6210 a7517b08 a7517b0c d44e8786 
    a7517b38:  00000002 d541f718 87025900 a7517b78 
    a7517b48:  e4afa018 00000438 e68f617c e589dd85 
    a7517b58:  00000000 000003e8 000001b8 00000000 
    a7517b68:  00000010 00000000 00000960 00000158 
    a7517b78:  87025900 00000000 00000000 00000000 
    a7517b88:  d44e8786 00000001 a7517c14 5b6b7b20 
    a7517b98:  00000001 5b6b7b68 a7517c18 e68f617c 
    a7517ba8:  5b6b7b48 e589c64f 00000001 00000001 
    a7517bb8:  00000b00 00000000 00000440 a7517bdc 
    a7517bc8:  00000000 00000960 00000178 00000002 
    a7517bd8:  a7517c10 923b7f60 d44e8786 e68f617c 
    a7517be8:  a7517c68 a7517ce0 e6c68f9d 66642a85 
    a7517bf8:  00000178 ba396bac 00000002 e6c68fc1 
    a7517c08:  a7517c28 e6875257 93b86538 00000178 
    a7517c18:  ba396bac d44e8786 93b86538 e5493edf 
    a7517c28:  00000002 e6875257 5b6b7b20 e58a7030 
    a7517c38:  a7517ce0 a7517c68 5b6b7b20 00000000 
    a7517c48:  e5480ff5 9058f8a8 e68f617c e4afd044 
    a7517c58:  e4afa018 e8132f69 00000000 ba395148 
    a7517c68:  00000000 ba396ba0 000001b8 000001b8 
    a7517c78:  000001b4 ba396d58 00000002 00000002 
    a7517c88:  00000002 00010001 00000000 ac010101 
    a7517c98:  e54898e1 ac1e7000 00000000 00000000 
    a7517ca8:  0c13da80 00000058 0000007e 00000058 
    a7517cb8:  00000000 00000000 00000000 00000000 
    a7517cc8:  e4010100 00000004 e4010001 00000000 
    a7517cd8:  e817383c 00000000 e6cf2958 5b6b7b20 
    a7517ce8:  d44e8786 9058f800 e68f617c 9058f8a8 
    a7517cf8:  00000006 9058f830 00000001 e815df1b 
    a7517d08:  00000960 00000001 00000200 00000000 
    a7517d18:  9058ff70 00000000 00000000 a7517e60 
    a7517d28:  a7517e5c 9058ff10 00000000 00000438 
    a7517d38:  e4afa018 e4afd044 e68f617c 00000000 
    a7517d48:  00000000 00000000 00000000 00000000 
    a7517d58:  00000000 00000000 00fe502b 00000000 
    a7517d68:  00fe502b 00000000 00000000 a2e2af58 
    a7517d78:  00000002 00000051 0000004f a5233110 
    a7517d88:  00000051 0000004f 7e56db10 9ed97300 
    a7517d98:  d44e8786 9ed97300 00000000 a7517e5c 
    a7517da8:  9ed97378 a7517e60 e68f617c 8f9ce168 
    a7517db8:  9ed97308 e4efd47f a7517de0 d44e8786 
    a7517dc8:  d44e8786 00003000 00000000 ca87688c 
    a7517dd8:  e4e8be29 64119650 e68f617c ca3f0c53 
    a7517de8:  e518b4a8 00000000 43ea0000 44a20000 
    a7517df8:  44190000 44a68000 d44e8786 d44e8786 
    a7517e08:  00000000 00000000 00000000 00000000 
    a7517e18:  00000000 00000000 00000000 d541f6d8 
    a7517e28:  ac1e7054 8aa97000 9b184140 e4e7d4e1 
    a7517e38:  00000000 e68f617c 00000960 a7518110 
    a7517e48:  00000000 e4e7e46b a7517f00 938cd7c0 
    a7517e58:  00000000 ffffffff 00000000 00000000 
    a7517e68:  00000438 a2e2af98 00000000 9d07c800 
    a7517e78:  00000000 adfd8b98 e68f617c 00000000 
    a7517e88:  00000003 639df880 d44e8786 00000028 
    a7517e98:  00000000 0000000b a84f0fcc 00000000 
    a7517ea8:  d44e8786 64119638 b92b0660 64119650 
    a7517eb8:  00003000 b92b0660 e68f617c 6411963c 
    a7517ec8:  b92b0660 ca3fe6cb 00000000 00000000 
    a7517ed8:  00000000 d097b440 3f800000 00000000 
    a7517ee8:  00000000 00000000 00000000 3f800000 
    a7517ef8:  968c3610 d44e8786 7cb97100 82af6584 
    a7517f08:  82af65a4 a7517f78 e68f617c e4afd044 
    a7517f18:  82af65ac e4e7f031 a7517f28 953e3f18 
    a7517f28:  a84f0fcc 00000000 d44e8786 d44e8786 
    a7517f38:  00000000 00000000 9058ff10 e4afa018 
    a7517f48:  d44e8786 64119638 64119638 d097b44c 
    a7517f58:  00003000 b92b0660 e68f617c 6411963c 
    a7517f68:  b92b0660 ca3fe4ab a751807c d097b440 
    a7517f78:  00003056 ca3f1451 a7518110 00000960 
    a7517f88:  00000438 d44e8786 a751807c d44e8786 
    a7517f98:  d097b4a0 64119638 d097b44c 00003000 
    a7517fa8:  a7518000 d097b440 0000313d ca3fbf4d 
    a7517fb8:  e6ded070 9c4308a0 a7518000 0000313d 
    a7517fc8:  e68f617c e68f617c 89ab4a00 e68f617c 
    a7517fd8:  e4afd044 e6dde6e5 00000001 e6ded048 
    a7517fe8:  d44e8786 9c4308a0 b29b98a0 a7518078 
    a7517ff8:  00000001 e4d8ac85 a7518078 d44e8786 
    a7518008:  a7518078 93fcf1e0 a7518078 89ab4a00 
    a7518018:  a7518088 e4d87cb1 a31c85a8 a76a52c0 
    a7518028:  89ab4a00 e4ed6965 00000001 e4ed67bb 
    a7518038:  e4afd044 e6ddcbd5 9c4308a0 b29b98a0 
    a7518048:  a7518070 0002cd7a e4afd044 e4ec2479 
    a7518058:  d44e8786 9058ff10 d44e8786 e68f617c 
    a7518068:  923b7fe0 e4ec2429 00000000 d44e8786 
    a7518078:  00000438 00000960 a31c8510 9c4308a0 
    a7518088:  43ea0000 44a20000 44190000 44a68000 
    a7518098:  e4afd044 e4ed63f7 a31c8518 a7518490 
    a75180a8:  00000019 a31c85a8 00000001 a31c8514 
    a75180b8:  89ab4a00 00000001 a31c8510 e4afa018 
    a75180c8:  e4afd044 e4ed60c9 b75a5708 e968e410 
    a75180d8:  cebbb510 e68f617c 653001d4 00000000 
    a75180e8:  e968e458 e968e440 00000001 00000003 
    a75180f8:  e968de00 cebbb078 cebbb000 923b7d20 
    a7518108:  00000000 b75a5708 00000000 e68f6101 
    a7518118:  89ab4a00 e688c101 89ab4a74 9e3ff000 
    a7518128:  00000002 00000000 89ab4aa0 00000000 
    a7518138:  00001200 00000001 00000438 00000960 
    a7518148:  01000000 e4f0ebff ffffffff ffffffff 
    a7518158:  a7518100 9e3ff000 d44e8700 00000008 
    a7518168:  d44e8786 923b7fe0 923b8000 923b7fe0 
    a7518178:  00000000 c241404b 000012f5 e94aeeb0 
    a7518188:  e68f617c e4edd1dd e94aeeb0 923b7fe0 
    a7518198:  923b8000 923b8000 d44e8786 e94aee60 
    a75181a8:  e94aeecc 00000000 00000001 a75181e4 
    a75181b8:  000012f5 e68f617c a7518230 e4edd037 
    a75181c8:  e94aee60 e94aee60 e94aee6c 00000000 
    a75181d8:  00000000 e8be4915 e94aee60 e94aee60 
    a75181e8:  b99bfd30 e94aee60 d44e8786 a7518230 
    a75181f8:  a7518230 a7518230 00000078 000012f5 
    a7518208:  000012f5 e9ade220 a7518230 e68e7549 
    a7518218:  e68e7533 e68a09f9 a7518238 e68e7533 
    a7518228:  a7518230 00000000 ac32b230 a5b2a230 
    a7518238:  000013ef 000012f5 00000001 a741b000 
    a7518248:  000fd230 00001000 00000000 00000000 
    a7518258:  00000003 00000000 e8be44f9 b99bfd50 
    a7518268:  00000000 cdc5d000 00000000 00000001 
    a7518278:  00000000 a741b000 00101000 00000000 
    a7518288:  a751828c 65646e75 656e6966 79732064 
    a7518298:  6c6f626d 6c67203a 706d6153 5072656c 
    a75182a8:  6d617261 72657465 00007669 00520052 
    a75182b8:  70006e6f 5845656c 00000054 00000000 
    a75182c8:  00000000 00000000 00000000 00000000 
    a75182d8:  00000000 00000000 00000000 00000000 
    a75182e8:  00000000 00000000 00000000 00000000 
    a75182f8:  00000000 00000000 00000000 00000000 
    a7518308:  00000000 00000000 00000000 00000000 
    a7518318:  00000000 00000000 00000000 00000000 
    a7518328:  00000000 00000000 00000000 00000000 
    a7518338:  00000000 00000000 00000000 00000000 
    a7518348:  00000000 00000000 00000000 00000000 
    a7518358:  00000000 00000000 00000000 00000000 
    a7518368:  00000000 00000000 00000000 00000000 
    a7518378:  00000000 00000000 00000000 00000000 
[DEBUG] reach max continuously zero line count: 12!
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
solib build id:
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libnative-imagetranscoder.so: de4cd35f9e6abc2153e7de8425b5a220a41dcae7
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libimagepipeline.so: bc9dbeaf5e5161944ff8d4d214ca102973bcd9f6
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libnetmonitor.so: b2710af23b86bb534bca87b7cc3878d5a3f44a12
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libijkffmpeg.so: (no build id)
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libijkplayer.so: 774329cc5035082213d9ab0598cd45692af3a291
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libliteavsdk.so: f68ef7efb5543d20a29743d757a09f114a1940d5
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libtxffmpeg.so: (no build id)
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libijksdl.so: 7299b47de3e3acf9d32b7056e35088248ef14dda
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libtraeimp-rtmp.so: 1650d29d86316813ae5bb0c9a4c9ffc80b9bd632
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libcrashsdk.so: d42c7ca182337c9a32edafeb03d784661b710375
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libgifimage.so: 391fe9400bc3695967c9cc76b9905894a6a9c096
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libsoundtouch.so: 5573d84e3f24d70b56c754555809e351fe5e453a
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libumeng-spy.so: 6745a23e4406f8602bf608b87e502cd37b94c349
/data/data/com.ymatou.shop/.jiagu/libjiagu.so: (no build id)
/data/app/com.ymatou.shop-GjzadqKHYF79d2OGOzAAyQ==/lib/arm/libA3AEECD8.so: (no build id)

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以使用 [在线支持](https://cloud.tencent.com/online-service?from=connect-us)。  
同时，您也可以拨打 95716 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
