### ISSUE TITLE
Custom Runtime 缺少文档

### ISSUE THREAD

**Issue by iugo** [tencentyun/qcloud-documents#9585]
文档正文: https://cloud.tencent.com/document/product/583/47274

这篇文档在仓库中找不到相关内容.

Custom Runtime 主要列举的是事件触发器, 但没有列举 HTTP 触发器的例子. 是和阿里云一样吗?

**Comment by cynth1ayang** [comment]
尊敬的腾讯云用户，您好！
Customruntime支持事件型函数，暂未支持Web函数。您可在 [CustomRuntime](https://github.com/tencentyun/qcloud-documents/tree/master/product/%E8%AE%A1%E7%AE%97%E4%B8%8E%E7%BD%91%E7%BB%9C/%E6%97%A0%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BA%91%E5%87%BD%E6%95%B0/%E4%BB%A3%E7%A0%81%E5%BC%80%E5%8F%91/CustomRuntime) 中查看相关文档。更多内容可查看 [API 网关触发器](https://cloud.tencent.com/document/product/583/12513)。
如果查看文档过程中，发现存在其它问题，欢迎继续在官网反馈，我们收到后会尽快处理。
如果遇到产品类问题，您可以通过 [在线咨询](https://cloud.tencent.com/online-service?from=connect-us) 来寻求帮助。
感谢您的支持，祝您工作顺利！
