### ISSUE TITLE
全球应用加速产品无产品动态页面

### ISSUE THREAD

**Issue by LHB6540** [tencentyun/qcloud-documents#9656]
全球应用加速产品无产品动态页面，无法快速获取产品动态和功能更新
产品文档url：https://cloud.tencent.com/document/product/608/13759

**Comment by vhyyhhu** [comment]
尊敬的腾讯云用户，您好！非常感谢您的反馈，您的建议我们已经收到，并已提交给相应团队进行评估，我们会尽快完成评估，并给您答复，非常感谢您！

**Comment by vhyyhhu** [comment]
已添加
