### ISSUE TITLE
增加suse、opensuse系统镜像吧

### ISSUE THREAD

**Issue by yyangdid** [tencentyun/qcloud-documents#9775]

**Comment by vyixzheng** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，但根据您提供的信息，暂时无法定位到问题。
为了能更方便、准确地定位问题，需要您补充多一点问题描述信息。例如，您需要 xxx 产品增加 xxx 镜像。
以便我们尽快核实后解决！
