### ISSUE TITLE
云游戏 pc端  锁定机器api的参数UserId 怎么获取？

### ISSUE THREAD

**Issue by shusenZhang** [tencentyun/qcloud-documents#9851]

**Comment by vyunyilin** [comment]
尊敬的腾讯云用户，您好！
非常感谢您的反馈，UserId 获取方式请参见 [创建会话接口](https://cloud.tencent.com/document/api/1162/40740)。
![image](https://user-images.githubusercontent.com/55578900/147182846-5f30ccb4-8df6-47eb-8bba-c81fd8dfd92f.png)
如果遇到产品使用等相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 来寻求帮助。
另外，您也可以拨打 4009100100 联系我们的客服人员，非常感谢！
