### ISSUE TITLE
   _LITEAV_ne10_init in TXLiteAVSDK_Player(NE10_init.o)

### ISSUE THREAD

**Issue by lizhaobomb** [tencentyun/qcloud-documents#9924]
Undefined symbols for architecture armv7:
  "_ne10_init_dsp", referenced from:
      _LITEAV_ne10_init in TXLiteAVSDK_Player(NE10_init.o)
ld: symbol(s) not found for architecture armv7

**Comment by dokieyang** [comment]
> Undefined symbols for architecture armv7: "_ne10_init_dsp", referenced from: _LITEAV_ne10_init in TXLiteAVSDK_Player(NE10_init.o) ld: symbol(s) not found for architecture armv7

请问可以提供更多信息吗？ 比如：机型， android系统版本，操作路径， 完整的log

**Comment by lizhaobomb** [comment]
> 

解决了，腾讯万象SDK的_all_load 依赖导致的，降了万象的版本
